force-app/main/default/objects/User_Access_Managment__c/User_Access_Managment__c.object-meta.xml
<CustomObject>
    <description>Object to Request user access to salesforce environments</description>
    <label>User Access Managment</label>
    <nameField>
        <displayFormat>UAR - {0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Access Managments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <inlineHelpText>Provide Access details Like Profile Name , Role , permission set details or user details with whom u would like to Mimic Your access</inlineHelpText>
    <label>Access Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Divsion__c.field-meta.xml
<CustomField>
    <fullName>Divsion__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>QE</fullName>
            </value>
            <value>
                <fullName>Product/Business</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Environments__c.field-meta.xml
<CustomField>
    <fullName>Environments__c</fullName>
    <label>Environments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC Dev1</fullName>
            </value>
            <value>
                <fullName>BRO</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>FSC INT</fullName>
            </value>
            <value>
                <fullName>FSC QA</fullName>
            </value>
            <value>
                <fullName>FSC UAT</fullName>
            </value>
            <value>
                <fullName>FSC PREPROD</fullName>
            </value>
            <value>
                <fullName>POC DEV1</fullName>
            </value>
            <value>
                <fullName>BRP POC</fullName>
                <isActive>false</isActive>
                <label>BRP POC</label>
            </value>
            <value>
                <fullName>EDJ GOV</fullName>
                <isActive>false</isActive>
                <label>EDJ GOV</label>
            </value>
            <value>
                <fullName>FSC SCALETEST</fullName>
                <isActive>false</isActive>
                <label>FSC SCALETEST</label>
            </value>
            <value>
                <fullName>Pioneer POC</fullName>
                <isActive>false</isActive>
                <label>Pioneer POC</label>
            </value>
            <value>
                <fullName>Training Org</fullName>
                <isActive>false</isActive>
                <label>Training Org</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Federation_ID__c.field-meta.xml
<CustomField>
    <fullName>Federation_ID__c</fullName>
    <label>Federation ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Product_Team__c.field-meta.xml
<CustomField>
    <fullName>Product_Team__c</fullName>
    <label>Product Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserAccessManagementecordRetriever.cls
public with sharing class UserAccessManagementecordRetriever {

    @AuraEnabled(cacheable=true)
    public static List<User_Access_Managment__c> getUserAccessManagementRecords() {
        return [
            SELECT Id, Name, Status__c, Product_Team__c, First_Name__c, Last_Name__c, Environments__c, Federation_ID__c, Email__c, Access_Details__c, Divsion__c 
            FROM User_Access_Managment__c 
            WHERE Status__c != 'Rejected' AND Status__c != 'Approved' AND Status__c != 'Provisioned'
        ];
    }

    @AuraEnabled
    public static String updateUserAccessRequests(String recordId, String selectedAction, String comments) {
       
        User_Access_Managment__c userAccessMan = [
            SELECT Id, Name, Status__c, Comments__c
            FROM User_Access_Managment__c
            WHERE Id = :recordId
            LIMIT 1
        ];
    
        if (userAccessMan != null) {
            userAccessMan.Status__c = selectedAction;
            userAccessMan.Comments__c = comments; 
            update userAccessMan;
            return 'Success';
        } else {
            return 'No record found';
        }
    }
}