force-app/main/default/objects/Case/fields/Issue_Environment__c.field-meta.xml
<CustomField>
    <fullName>Issue_Environment__c</fullName>
    <inlineHelpText>Please provide the environment where the issue is.</inlineHelpText>
    <label>Issue Environment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INT</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>UAT 2</fullName>
            </value>
            <value>
                <fullName>PreProd</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please provide the team the issue belongs to.</inlineHelpText>
    <label>Team</label>
    <referenceTo>copado__Team__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/Issue_Tracker__c.object-meta.xml
<CustomObject>
    <description>This object is used for Copado Issues Tracking for Dev and DevOps</description>
    <label>Issue Tracker</label>
    <nameField>
        <displayFormat>IT-{000000}</displayFormat>
        <label>Issue Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Tracker__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Please provide the category of the Issue.</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code Override</fullName>
            </value>
            <value>
                <fullName>Commit Issue</fullName>
            </value>
            <value>
                <fullName>Merge Issue</fullName>
            </value>
            <value>
                <fullName>Developer Support</fullName>
            </value>
            <value>
                <fullName>Environment Issue</fullName>
            </value>
            <value>
                <fullName>Deployment Issue</fullName>
            </value>
            <value>
                <fullName>Tooling</fullName>
            </value>
            <value>
                <fullName>OmniStudio Issue</fullName>
            </value>
            <value>
                <fullName>User Setup</fullName>
            </value>
            <value>
                <fullName>User Creation</fullName>
            </value>
            <value>
                <fullName>Knowledge Issue</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Issue_Description__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description__c</fullName>
    <label>Issue Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Issue_Environment__c.field-meta.xml
<CustomField>
    <fullName>Issue_Environment__c</fullName>
    <inlineHelpText>Please select the environment to which the issue is applicable.</inlineHelpText>
    <label>Issue Environment</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Environments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Provide the Issue Priority.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
            </value>
            <value>
                <fullName>P5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>copado__Team__c</referenceTo>
    <relationshipLabel>Issue Tracker</relationshipLabel>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>Users team name.</description>
    <inlineHelpText>Name of the team that user belongs to</inlineHelpText>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CloudFulcrum Team</fullName>
            </value>
            <value>
                <fullName>Financial Service Team</fullName>
            </value>
            <value>
                <fullName>Service Team</fullName>
            </value>
            <value>
                <fullName>Salesforce Automated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/User_Access_Managment__c.object-meta.xml
<CustomObject>
    <description>Object to Request user access to salesforce environments</description>
    <label>User Access Managment</label>
    <nameField>
        <displayFormat>UAR - {0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Access Managments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <inlineHelpText>Provide Access details Like Profile Name , Role , permission set details or user details with whom u would like to Mimic Your access</inlineHelpText>
    <label>Access Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Divsion__c.field-meta.xml
<CustomField>
    <fullName>Divsion__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>QE</fullName>
            </value>
            <value>
                <fullName>Product/Business</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/End_of_Day__c.field-meta.xml
<CustomField>
    <fullName>End_of_Day__c</fullName>
    <label>End of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Environments__c.field-meta.xml
<CustomField>
    <fullName>Environments__c</fullName>
    <label>Environments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC Dev1</fullName>
            </value>
            <value>
                <fullName>BRO</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>FSC INT</fullName>
            </value>
            <value>
                <fullName>FSC QA</fullName>
            </value>
            <value>
                <fullName>FSC UAT</fullName>
            </value>
            <value>
                <fullName>FSC PREPROD</fullName>
            </value>
            <value>
                <fullName>POC DEV1</fullName>
            </value>
            <value>
                <fullName>BRP POC</fullName>
                <isActive>false</isActive>
                <label>BRP POC</label>
            </value>
            <value>
                <fullName>EDJ GOV</fullName>
                <isActive>false</isActive>
                <label>EDJ GOV</label>
            </value>
            <value>
                <fullName>FSC SCALETEST</fullName>
                <isActive>false</isActive>
                <label>FSC SCALETEST</label>
            </value>
            <value>
                <fullName>Pioneer POC</fullName>
                <isActive>false</isActive>
                <label>Pioneer POC</label>
            </value>
            <value>
                <fullName>Training Org</fullName>
                <isActive>false</isActive>
                <label>Training Org</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Federation_ID__c.field-meta.xml
<CustomField>
    <fullName>Federation_ID__c</fullName>
    <label>Federation ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Product_Team__c.field-meta.xml
<CustomField>
    <fullName>Product_Team__c</fullName>
    <label>Product Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Start_Of_Day__c.field-meta.xml
<CustomField>
    <fullName>Start_Of_Day__c</fullName>
    <defaultValue>TEXT(TIMEVALUE(&apos;01:00&apos;))</defaultValue>
    <label>Start Of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone fo the user</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Kolkata)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:30) Newfoundland Standard Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-02:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Atlantic Standard Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:00) Atlantic Daylight Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Alaska Standard Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Alaska Daylight Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Hawaii-Aleutian Daylight Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Honolulu)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Johnston)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Environments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DEV</fullName>
    </customValue>
    <customValue>
        <fullName>INT</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <customValue>
        <fullName>UAT2</fullName>
    </customValue>
    <customValue>
        <fullName>PreProd</fullName>
    </customValue>
    <customValue>
        <fullName>PROD</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>ScaleTest</fullName>
    </customValue>
    <masterLabel>Environments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserAccessManagementControllerTest.cls
@isTest
public class UserAccessManagementControllerTest {
    
    @isTest
    static void testCreateUserAccessRecord_Success() {
        // Create a valid User_Access_Managment__c record
        User_Access_Managment__c objUser = new User_Access_Managment__c(Access_Details__c = 'Valid Access Details', First_Name__c = 'FirstTest',
                                                                        Last_Name__c = 'SecondTest', Email__c = 'test@test.com',
                                                                        Time_Zone__c = '(GMT-03:00) Atlantic Daylight Time (America/Halifax)',
                                                                        Divsion__c = 'FA', Product_Team__c = 'FSC',
                                                                        Start_Of_Day__c = '00:00', End_of_Day__c = '17:00',
                                                                        Federation_ID__c = 'ASZE12', Environments__c = 'FSC QA');
        
        String userType = 'New User Request'; // Set the userType
        
        // Call the method and assert the result
        Test.startTest();
        String result = UserAccessManagementController.createUserAccessRecord(objUser, userType);
        Test.stopTest();
        
        // Assert that the record was created and the name was returned
        System.assertNotEquals(objUser.Name, result);
        System.assertEquals(objUser.Environments__c, 'FSC QA');
    }
    
    @isTest
    static void testGetStartOfDayPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getStartOfDayPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testGetProductTeamPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getProductTeamPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testGetDivisionPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getDivisionPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testGetTimeZonePicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getTimeZonePicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testGetEnvPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getEnvPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testGetPersonaPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getPersonaPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testCreateUserAccessRecord_Exception() {
        // Create a User_Access_Managment__c record with missing required fields to trigger an exception
        User_Access_Managment__c objUser = new User_Access_Managment__c(
            Access_Details__c = 'Test Access',
            First_Name__c = 'TestFirst'
            // Missing required fields like Email__c
        );
        String userType = 'New User Request';
        
        Test.startTest();
        try {
            String result = UserAccessManagementController.createUserAccessRecord(objUser, userType);
            //System.assert(false, 'Exception was expected but not thrown.');
        } catch (Exception e) {
            // Assert that an exception was caught
            System.assert(e.getMessage().contains('required'), 'Expected error message.');
        }
        Test.stopTest();
    }
    
    @isTest
    static void testSearchUsers() {
        User testUser = new User(FirstName = 'Sivaji', LastName = 'CF', Username = 'sivajict@test.com', Email = 'sivajicf@test.com',
                                 Alias = 'sicf', ProfileId = [SELECT Id FROM Profile LIMIT 1].Id, TimeZoneSidKey = 'America/Los_Angeles',
                                 LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US');
        insert testUser;
        
        Test.startTest();
        List<User> users = UserAccessManagementController.searchUsers('Sivaji');
        Test.stopTest();
        
        // Assert that the user is found
        System.assert(users.size() > 0, 'Expected user to be returned.');
        System.assertEquals(testUser.Id, users[0].Id, 'Expected the correct user to be returned.');
    }
    /*
    // Issuse Tracking Test Case Methods
    @isTest
    static void testGetCategoryPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getCategoryPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    }
    
    @isTest
    static void testGetPriorityPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getPriorityPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    } 
    
    @isTest
    static void testGetEnvironmentPicklistValues() {
        Test.startTest();
        List<String> values = UserAccessManagementController.getEnvironmentPicklistValues();
        Test.stopTest();
        
        // Assert that the picklist values were retrieved
        System.assertNotEquals(null, values);
        System.assert(values.size() > 0);
    } 
    
    // Issue Tracker
    @isTest
    static void testCreateIssueTrackerRecord_Success() {
        
        // Create a valid Team record (assuming Team__c is a lookup/master-detail field)
        copado__Team__c team = new copado__Team__c(Name = 'Test Team');
        insert team;
        
        // Create a valid Issue_Tracker__c record
        Issue_Tracker__c issueObj = new Issue_Tracker__c(Issue_Description__c = 'Test Issue Description',Issue_Environment__c = 'INT',
                                                         Priority__c = 'P3', Category__c = 'Tooling',Team__c = 'a1r7d0000086FiWAAU');
        
        Test.startTest();
        String result = UserAccessManagementController.createIssueTrackerRecord(issueObj);
        Test.stopTest();
        
        // Assert that the record was created and 'success' was returned
        System.assertEquals('success', result);
        System.assertNotEquals(null, issueObj.Id);
    }
    
    //Adding Method
    @isTest
    static void testCreateIssueTrackerRecord_Exception() {
        // Create an Issue_Tracker__c record with invalid data to trigger an exception
        Issue_Tracker__c issueObj = new Issue_Tracker__c(
            // Missing required fields, such as Category__c, to simulate failure
            Issue_Description__c = 'Test Issue Description'
        );
        
        Test.startTest();
        String result = UserAccessManagementController.createIssueTrackerRecord(issueObj);
        Test.stopTest();
        
        // Assert that an error message was returned
        System.assert(result.startsWith('Error: '), 'Expected error message.');
    }
    
    @isTest
    static void testGetTeams() {
        // Step 1: Create mock copado__Team__c records
        List<copado__Team__c> teams = new List<copado__Team__c>();
        teams.add(new copado__Team__c(Name = 'Team A'));
        teams.add(new copado__Team__c(Name = 'Team B'));
        teams.add(new copado__Team__c(Name = 'Team C'));
        
        // Insert the mock team records
        insert teams;
        
        // Step 2: Call the getTeams method
        Test.startTest();
        List<UserAccessManagementController.IdNameWrapper> result = UserAccessManagementController.getTeams();
        Test.stopTest();
        
        // Step 3: Verify the results
        System.assertEquals(3, result.size(), 'Expected 3 teams in the result list');
        
        // Check if the team names and IDs match
        System.assertEquals(teams[0].Id, result[0].id, 'First team ID should match');
        System.assertEquals('Team A', result[0].name, 'First team name should be Team A');
    } */
    
}