force-app/main/default/objects/PMD_Report__mdt/PMD_Report__mdt.object-meta.xml
<CustomObject>
    <label>PMD Report</label>
    <pluralLabel>PMD Reports</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMD_Report__mdt/fields/Org_Address__c.field-meta.xml
<CustomField>
    <fullName>Org_Address__c</fullName>
    <label>Org Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/User_Access_Managment__c.object-meta.xml
<CustomObject>
    <description>Object to Request user access to salesforce environments</description>
    <label>User Access Managment</label>
    <nameField>
        <displayFormat>UAR - {0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Access Managments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <inlineHelpText>Provide Access details Like Profile Name , Role , permission set details or user details with whom u would like to Mimic Your access</inlineHelpText>
    <label>Access Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Access_Period_End__c</fullName>
    <label>Access Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Access_Period_Start__c</fullName>
    <label>Access Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Addition_of_Permission__c.field-meta.xml
<CustomField>
    <fullName>Addition_of_Permission__c</fullName>
    <label>Addition of Permission</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/DevOps__c.field-meta.xml
<CustomField>
    <fullName>DevOps__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DevOps</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Access_Managments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Divsion__c.field-meta.xml
<CustomField>
    <fullName>Divsion__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>QE</fullName>
            </value>
            <value>
                <fullName>Product/Business</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/End_of_Day__c.field-meta.xml
<CustomField>
    <fullName>End_of_Day__c</fullName>
    <label>End of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Environments__c.field-meta.xml
<CustomField>
    <fullName>Environments__c</fullName>
    <label>Environments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC Dev1</fullName>
            </value>
            <value>
                <fullName>BRO</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>FSC INT</fullName>
            </value>
            <value>
                <fullName>FSC QA</fullName>
            </value>
            <value>
                <fullName>FSC UAT</fullName>
            </value>
            <value>
                <fullName>FSC PREPROD</fullName>
            </value>
            <value>
                <fullName>POC DEV1</fullName>
            </value>
            <value>
                <fullName>BRP POC</fullName>
                <isActive>false</isActive>
                <label>BRP POC</label>
            </value>
            <value>
                <fullName>EDJ GOV</fullName>
                <isActive>false</isActive>
                <label>EDJ GOV</label>
            </value>
            <value>
                <fullName>FSC SCALETEST</fullName>
                <isActive>false</isActive>
                <label>FSC SCALETEST</label>
            </value>
            <value>
                <fullName>Pioneer POC</fullName>
                <isActive>false</isActive>
                <label>Pioneer POC</label>
            </value>
            <value>
                <fullName>Training Org</fullName>
                <isActive>false</isActive>
                <label>Training Org</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Federation_ID__c.field-meta.xml
<CustomField>
    <fullName>Federation_ID__c</fullName>
    <label>Federation ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <inlineHelpText>Comprising permission set, profile, permission set group, and territory</inlineHelpText>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Advisor (FA)</fullName>
            </value>
            <value>
                <fullName>Branch Office Administrator (BOA)</fullName>
            </value>
            <value>
                <fullName>Home Office 1</fullName>
            </value>
            <value>
                <fullName>Legal/Field Supervision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>HQIS</fullName>
                <isActive>false</isActive>
                <label>HQIS</label>
            </value>
            <value>
                <fullName>Home Office 2</fullName>
                <isActive>false</isActive>
                <label>Home Office 2</label>
            </value>
            <value>
                <fullName>System Admin Read Only</fullName>
                <isActive>false</isActive>
                <label>System Admin Read Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Product_Team__c.field-meta.xml
<CustomField>
    <fullName>Product_Team__c</fullName>
    <label>Product Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Reference_User__c.field-meta.xml
<CustomField>
    <fullName>Reference_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Access_Managments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Removal_of_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Removal_of_Permissions__c</fullName>
    <label>Removal of Permissions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New User Request</fullName>
            </value>
            <value>
                <fullName>Existing User Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Start_Of_Day__c.field-meta.xml
<CustomField>
    <fullName>Start_Of_Day__c</fullName>
    <defaultValue>TEXT(TIMEVALUE(&apos;01:00&apos;))</defaultValue>
    <label>Start Of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone fo the user</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Kolkata)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:30) Newfoundland Standard Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-02:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Atlantic Standard Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:00) Atlantic Daylight Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Alaska Standard Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Alaska Daylight Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Hawaii-Aleutian Daylight Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Honolulu)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Johnston)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserAccessRecordRetriever.cls
public with sharing class UserAccessRecordRetriever {

    // Wrapper for devOps data and User Access Management record fields
    public class devopsWrapper {
        @AuraEnabled public String devOpsName { get; set; }
        @AuraEnabled public Id recordId { get; set; }
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String fullName { get; set; }    // Concatenated Full Name
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public String productTeam { get; set; }
        @AuraEnabled public String firstName { get; set; }
        @AuraEnabled public String lastName { get; set; }
        @AuraEnabled public String environments { get; set; }
        @AuraEnabled public String federationId { get; set; }
        @AuraEnabled public String email { get; set; }
        @AuraEnabled public String accessDetails { get; set; }
        @AuraEnabled public String division { get; set; }
        @AuraEnabled public Date accessPeriodStart { get; set; }
        @AuraEnabled public Date accessPeriodEnd { get; set; }
        @AuraEnabled public String additionOfPermission { get; set; }
        @AuraEnabled public String removalOfPermission { get; set; }
        @AuraEnabled public String endOfDay { get; set; }
        @AuraEnabled public String startOfDay { get; set; }
        @AuraEnabled public String persona { get; set; }
        @AuraEnabled public String referenceUser { get; set; }
        @AuraEnabled public String timeZone { get; set; }
        @AuraEnabled public String requestType { get; set; }
        
        // Constructor to initialize wrapper class
        public devopsWrapper(User_Access_Managment__c userAccessRecord) {
            this.devOpsName = userAccessRecord.DevOps__r != null ? userAccessRecord.DevOps__r.Name : null;
            this.recordId = userAccessRecord.Id;
            this.name = userAccessRecord.Name;
            this.fullName = userAccessRecord.First_Name__c + ' ' + userAccessRecord.Last_Name__c;
            this.status = userAccessRecord.Status__c;
            this.productTeam = userAccessRecord.Product_Team__c;
            this.firstName = userAccessRecord.First_Name__c;
            this.lastName = userAccessRecord.Last_Name__c;
            this.environments = userAccessRecord.Environments__c;
            this.federationId = userAccessRecord.Federation_ID__c;
            this.email = userAccessRecord.Email__c;
            this.accessDetails = userAccessRecord.Access_Details__c;
            this.division = userAccessRecord.Divsion__c;
            this.accessPeriodStart = userAccessRecord.Access_Period_Start__c;
            this.accessPeriodEnd = userAccessRecord.Access_Period_End__c;
            this.additionOfPermission = userAccessRecord.Addition_of_Permission__c;
            this.removalOfPermission = userAccessRecord.Removal_of_Permissions__c;
            this.endOfDay = userAccessRecord.End_of_Day__c;
            this.startOfDay = userAccessRecord.Start_Of_Day__c;
            this.persona = userAccessRecord.Persona__c;
            this.referenceUser = userAccessRecord.Reference_User__c;
            this.timeZone = userAccessRecord.Time_Zone__c;
            this.requestType = userAccessRecord.Request_Type__c;
        }
    }

    // Method to display all records with Status 'Requested' and 'Approved' in LWC
    @AuraEnabled(cacheable=true)
    public static List<devopsWrapper> getUserAccessManagementRecords() {
        List<User_Access_Managment__c> userAccessRecords = [SELECT Id, Name, Status__c, Product_Team__c, First_Name__c, Last_Name__c, 
                                                            Environments__c, Federation_ID__c, Email__c, Access_Details__c, Divsion__c, 
                                                            Access_Period_End__c, Access_Period_Start__c, Addition_of_Permission__c, 
                                                            End_of_Day__c, Persona__c, Reference_User__c, Removal_of_Permissions__c, 
                                                            Start_Of_Day__c, Time_Zone__c, DevOps__r.Name, Request_Type__c
                                                            FROM User_Access_Managment__c WHERE Status__c != 'Completed'
                                                            ORDER BY CreatedDate DESC];
        System.debug('User Access Records: +++++ ' + userAccessRecords);
        List<devopsWrapper> wrapperList = new List<devopsWrapper>();
        for (User_Access_Managment__c record : userAccessRecords) {
            wrapperList.add(new devopsWrapper(record));
        }
        System.debug('Wrapper List: ++++ ' + wrapperList);
        return wrapperList;
    }

    // Method to generate the CSV report and send an email
    public static void sendWeeklyUserAccessReport() {
        // SOQL Query to fetch records for the last 7 days
        List<User_Access_Managment__c> userAccessReport = [SELECT Id, Name, Status__c, Product_Team__c, First_Name__c, Last_Name__c, 
                                                            Environments__c, Federation_ID__c, Email__c, Access_Details__c, Divsion__c, 
                                                            Access_Period_End__c, Access_Period_Start__c, Addition_of_Permission__c, 
                                                            End_of_Day__c, Persona__c, Reference_User__c, Removal_of_Permissions__c, 
                                                            Start_Of_Day__c, Time_Zone__c, DevOps__r.Name, Request_Type__c
                                                            FROM User_Access_Managment__c WHERE CreatedDate = LAST_N_DAYS:7 
                                                            ORDER BY CreatedDate DESC];
        System.debug('Weekly User Access Report' + userAccessReport);
        // Initialize CSV data
        String csvData = 'SNo,Request Type,Requested By,Environments,Division,Persona\n';
        Integer sno = 1;
        Integer newCount = 0, existCount = 0;

        for (User_Access_Managment__c record : userAccessReport) {
            devopsWrapper wrapper = new devopsWrapper(record);
            csvData += sno + ',' + wrapper.requestType + ',' + wrapper.fullName + ',' + wrapper.environments + ',' + 
                        wrapper.division + ',' + wrapper.persona + '\n';
            sno++;

            if (wrapper.requestType == 'New User Request') {
                newCount++;
            } else if (wrapper.requestType == 'Existing User Request') {
                existCount++;
            }
        }
        System.debug('Generated CSV data' + csvData);
        // Create HTML body for the email
        String htmlBody = 'Hi Team, <br><br>Here\'s the report generated for the Weekly User Access Requests. ' +
                          'Please find the following Details:<br><br>' +
                          '<table border="1" style="border-collapse: collapse; text-align: center;">' +
                          '<tr>' +
                          '<th style="background-color: #f2f2f2; padding: 8px;">Total Number of Requests</th>' +
                          '<th style="background-color: #f2f2f2; padding: 8px;">New User Requests</th>' +
                          '<th style="background-color: #f2f2f2; padding: 8px;">Existing User Requests</th>' +
                          '</tr>' +
                          '<tr>' +
                          '<td style="padding: 8px;">' + userAccessReport.size() + '</td>' +
                          '<td style="padding: 8px;">' + newCount + '</td>' +
                          '<td style="padding: 8px;">' + existCount + '</td>' +
                          '</tr></table><br>Please find the Attachment. <br><br> Regards,<br>DevOps Team';

        // Create CSV email attachment
        Messaging.EmailFileAttachment csvAttachment = new Messaging.EmailFileAttachment();
        Blob csvBlob = Blob.valueOf(csvData);
        csvAttachment.setFileName('UserAccessRequestReport.csv');
        csvAttachment.setBody(csvBlob);

        // Call the method to send email with the CSV attachment
        sendEmailWithAttachment(csvAttachment, htmlBody);
    }

    public static void sendEmailWithAttachment(Messaging.EmailFileAttachment csvAttachment, String htmlBody) {
        List<String> emailAddresses = new List<String>();
        
        // Fetch PMD_Report__mdt records
        List<PMD_Report__mdt> pmdReportList = [SELECT Id, Org_Address__c, Email_Address__c FROM PMD_Report__mdt LIMIT 1];
        PMD_Report__mdt pmdReport = pmdReportList[0];
        System.debug('PMD Report Email Address +++++ ' + pmdReportList);
        
        // Fetch OrgWideEmailAddress
        List<OrgWideEmailAddress> orgAddressList = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress 
                                                    WHERE DisplayName = :pmdReport.Org_Address__c LIMIT 1];
        OrgWideEmailAddress orgAddress = (orgAddressList.size() > 0) ? orgAddressList[0] : null;
        System.debug('OrgWideEmailAddress: +++++ ' + orgAddress);

        if (orgAddress == null) {
            System.debug('No OrgWideEmailAddress found with display name: ' + pmdReport.Org_Address__c);
            return;
        }

        // Create email
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        emailAddresses.addAll(pmdReport.Email_Address__c.split(','));
        email.setToAddresses(emailAddresses);
        email.setOrgWideEmailAddressId(orgAddress.Id);
        email.setSubject('User Access Management Report');
        email.setHtmlBody(htmlBody);
        email.setFileAttachments(new Messaging.EmailFileAttachment[] { csvAttachment });

        // Send email
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }
}


    /*
    @AuraEnabled
    public static String updateUserAccessRequests(String recordId, String selectedAction, String comments) {
        
        User_Access_Managment__c userAccessMan = [SELECT Id, Name, Status__c, Comments__c 
												  FROM User_Access_Managment__c WHERE Id = :recordId LIMIT 1];
        
        if (userAccessMan != null) {
            userAccessMan.Status__c = selectedAction;
            userAccessMan.Comments__c = comments; 
            update userAccessMan;
            return 'Success';
        } else {
            return 'No record found';
        }
    } 
	*/