force-app/main/default/objects/PMD_Report__mdt/PMD_Report__mdt.object-meta.xml
<CustomObject>
    <label>PMD Report</label>
    <pluralLabel>PMD Reports</pluralLabel>
</CustomObject>

force-app/main/default/objects/PMD_Report__mdt/fields/Org_Address__c.field-meta.xml
<CustomField>
    <fullName>Org_Address__c</fullName>
    <label>Org Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/User_Access_Managment__c.object-meta.xml
<CustomObject>
    <description>Object to Request user access to salesforce environments</description>
    <label>User Access Managment</label>
    <nameField>
        <displayFormat>UAR - {0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Access Managments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Details__c.field-meta.xml
<CustomField>
    <fullName>Access_Details__c</fullName>
    <inlineHelpText>Provide Access details Like Profile Name , Role , permission set details or user details with whom u would like to Mimic Your access</inlineHelpText>
    <label>Access Details</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Period_End__c.field-meta.xml
<CustomField>
    <fullName>Access_Period_End__c</fullName>
    <label>Access Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Access_Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Access_Period_Start__c</fullName>
    <label>Access Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Addition_of_Permission__c.field-meta.xml
<CustomField>
    <fullName>Addition_of_Permission__c</fullName>
    <label>Addition of Permission</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Divsion__c.field-meta.xml
<CustomField>
    <fullName>Divsion__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>QE</fullName>
            </value>
            <value>
                <fullName>Product/Business</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/End_of_Day__c.field-meta.xml
<CustomField>
    <fullName>End_of_Day__c</fullName>
    <label>End of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Environments__c.field-meta.xml
<CustomField>
    <fullName>Environments__c</fullName>
    <label>Environments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC Dev1</fullName>
            </value>
            <value>
                <fullName>BRO</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>FSC INT</fullName>
            </value>
            <value>
                <fullName>FSC QA</fullName>
            </value>
            <value>
                <fullName>FSC UAT</fullName>
            </value>
            <value>
                <fullName>FSC PREPROD</fullName>
            </value>
            <value>
                <fullName>POC DEV1</fullName>
            </value>
            <value>
                <fullName>BRP POC</fullName>
                <isActive>false</isActive>
                <label>BRP POC</label>
            </value>
            <value>
                <fullName>EDJ GOV</fullName>
                <isActive>false</isActive>
                <label>EDJ GOV</label>
            </value>
            <value>
                <fullName>FSC SCALETEST</fullName>
                <isActive>false</isActive>
                <label>FSC SCALETEST</label>
            </value>
            <value>
                <fullName>Pioneer POC</fullName>
                <isActive>false</isActive>
                <label>Pioneer POC</label>
            </value>
            <value>
                <fullName>Training Org</fullName>
                <isActive>false</isActive>
                <label>Training Org</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Federation_ID__c.field-meta.xml
<CustomField>
    <fullName>Federation_ID__c</fullName>
    <label>Federation ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <inlineHelpText>Comprising permission set, profile, permission set group, and territory</inlineHelpText>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Advisor (FA)</fullName>
            </value>
            <value>
                <fullName>Branch Office Administrator (BOA)</fullName>
            </value>
            <value>
                <fullName>Home Office 1</fullName>
            </value>
            <value>
                <fullName>Legal/Field Supervision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>HQIS</fullName>
                <isActive>false</isActive>
                <label>HQIS</label>
            </value>
            <value>
                <fullName>Home Office 2</fullName>
                <isActive>false</isActive>
                <label>Home Office 2</label>
            </value>
            <value>
                <fullName>System Admin Read Only</fullName>
                <isActive>false</isActive>
                <label>System Admin Read Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Product_Team__c.field-meta.xml
<CustomField>
    <fullName>Product_Team__c</fullName>
    <label>Product Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Reference_User__c.field-meta.xml
<CustomField>
    <fullName>Reference_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Access_Managments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Removal_of_Permissions__c.field-meta.xml
<CustomField>
    <fullName>Removal_of_Permissions__c</fullName>
    <label>Removal of Permissions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New User Request</fullName>
            </value>
            <value>
                <fullName>Existing User Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Start_Of_Day__c.field-meta.xml
<CustomField>
    <fullName>Start_Of_Day__c</fullName>
    <defaultValue>TEXT(TIMEVALUE(&apos;01:00&apos;))</defaultValue>
    <label>Start Of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone fo the user</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Kolkata)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:30) Newfoundland Standard Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-02:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Atlantic Standard Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:00) Atlantic Daylight Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Alaska Standard Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Alaska Daylight Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Hawaii-Aleutian Daylight Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Honolulu)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Johnston)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserAccessRecordRetrieverTest.cls
@isTest
public class UserAccessRecordRetrieverTest {
    
    @isTest
    static void testGetUserAccessManagementRecords() {
        // Create a user reference
        User referenceUser = new User(LastName = 'ReferenceUser', Alias = 'refuser', Email = 'refusr@example.com',
                                      Username = 'refusr@example.com',
                                      ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id,
                                      LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US',
                                      TimeZoneSidKey = 'Asia/Kolkata'
                                     );
        insert referenceUser;
        
        // Create a test User_Access_Managment__c record
        User_Access_Managment__c testUserAccess = new 
            User_Access_Managment__c(Status__c = 'Requested', Product_Team__c = 'FSC', 
                                     First_Name__c = 'Test', Last_Name__c = 'User1',
                                     Environments__c = 'FSC Dev1', Federation_ID__c = 'P456721', 
                                     Email__c = 'testuser1@example.com', Access_Details__c = 'Test', 
                                     Divsion__c = 'DevOps', Access_Period_Start__c = Date.today(),
                                     Access_Period_End__c = Date.today().addDays(30), Addition_of_Permission__c = 'Permission A',
                                     Removal_of_Permissions__c = 'Permission B', End_of_Day__c = '17:00', 
                                     Start_Of_Day__c = '09:00', Persona__c = 'Branch Office Administrator (BOA)',
                                     Time_Zone__c = '(GMT-03:00) Atlantic Daylight Time (America/Halifax)',
                                     Reference_User__c = referenceUser.Id,        // Use the dynamically created user
                                     Request_Type__c = 'New User Request'
                                    );
        insert testUserAccess;
        
        // Create mock OrgWideEmailAddress
        OrgWideEmailAddress orgEmail = new OrgWideEmailAddress();
        orgEmail.Address = 'test@example.com';
        orgEmail.DisplayName = 'CF-EJ-FSCDEVOPS';
        
        // Create mock PMD_Report__mdt records
        PMD_Report__mdt mockReport = new PMD_Report__mdt();
        mockReport.Org_Address__c = orgEmail.Address; // Set the Org Address
        mockReport.Email_Address__c = 'test@example.com'; // Use the same address
        // Note: Do not insert OrgWideEmailAddress and PMD_Report__mdt in test, it should exist in org
        // Start test for getUserAccessManagementRecords
        Test.startTest();
        List<UserAccessRecordRetriever.devopsWrapper> results = UserAccessRecordRetriever.getUserAccessManagementRecords();
        Test.stopTest();
        
        // Assert results
        System.assertNotEquals(0, results.size(), 'Expected results to be returned.');
    }
    
    @isTest
    static void testSendWeeklyUserAccessReport() {
        
        // Create mock OrgWideEmailAddress
        OrgWideEmailAddress orgEmail = new OrgWideEmailAddress();
        orgEmail.Address = 'test@example.com';
        orgEmail.DisplayName = 'CF-EJ-FSCDEVOPS';
        
        // Create mock PMD_Report__mdt records
        PMD_Report__mdt mockReport = new PMD_Report__mdt();
        mockReport.Org_Address__c = orgEmail.Address; // Set the Org Address
        mockReport.Email_Address__c = 'test@example.com'; // Use the same address
        
        // Insert User_Access_Managment__c record for testing
        User_Access_Managment__c testUserAccess = new 
            User_Access_Managment__c(Status__c = 'Requested', Product_Team__c = 'FSC', First_Name__c = 'Test', 
                                     Last_Name__c = 'User1',Environments__c = 'FSC Dev1', Federation_ID__c = 'P456721', 
                                     Email__c = 'testuser1@example.com', Access_Details__c = 'Test', Divsion__c = 'DevOps', 
                                     Access_Period_Start__c = Date.today(), Access_Period_End__c = Date.today().addDays(30));
        insert testUserAccess;
        
        // Start test for sendWeeklyUserAccessReport
        Test.startTest();
        UserAccessRecordRetriever.sendWeeklyUserAccessReport();
        Test.stopTest();
    }
}