force-app/main/default/objects/Release_Assignment__c/Release_Assignment__c.object-meta.xml
<CustomObject>
    <label>Release Assignment</label>
    <nameField>
        <displayFormat>RAN-{000000}</displayFormat>
        <label>Release Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Assignment__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Assignments</relationshipLabel>
    <relationshipName>Release_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Lead</fullName>
            </value>
            <value>
                <fullName>Tech Lead</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Dev Lead</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
            <value>
                <fullName>FSC PO</fullName>
            </value>
            <value>
                <fullName>DevOps Lead</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/Release_Playbook__c.object-meta.xml
<CustomObject>
    <label>Release Playbook</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Release Playbook Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/Release_Playbook_Item__c.object-meta.xml
<CustomObject>
    <label>Release Playbook Item</label>
    <nameField>
        <displayFormat>RPI-{000000}</displayFormat>
        <label>Release Playbook Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbook Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program Governance</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preprod</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Execution_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Execution_Sequence__c</fullName>
    <label>Execution Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before Deployment</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>After Deployment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Issues_Comments__c.field-meta.xml
<CustomField>
    <fullName>Issues_Comments__c</fullName>
    <label>Issues/Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Playbook Items</relationshipLabel>
    <relationshipName>Release_Playbook_Items1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Prod Deployment</fullName>
            </value>
            <value>
                <fullName>Pre-Deployment</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Go Live</fullName>
            </value>
            <value>
                <fullName>Post Go Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Task_Description__c.field-meta.xml
<CustomField>
    <fullName>Task_Description__c</fullName>
    <label>Task Description</label>
    <length>50768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ReleasePlaybookControllerTest.cls
@isTest
public class ReleasePlaybookControllerTest {
    
    @testSetup
    static void setupTestData() {
        // Create test data for Release_Playbook__c
        RecordType rtTemplate = [SELECT Id FROM RecordType WHERE Name = 'Release Playbook Template' AND SObjectType = 'Release_Playbook__c' LIMIT 1];
        RecordType rtItemTemplate = [SELECT Id FROM RecordType WHERE Name = 'Release Item Templates' AND SObjectType = 'Release_Playbook_Item__c' LIMIT 1];
        RecordType rtAssignment = [SELECT Id FROM RecordType WHERE Name = 'Template Release Assignments' AND SObjectType = 'Release_Assignment__c' LIMIT 1];
        RecordType rtReleasePlaybook = [SELECT Id FROM RecordType WHERE Name = 'Release Playbook' AND SObjectType = 'Release_Playbook__c' LIMIT 1];
        
        Release_Playbook__c playbookTemplate = new Release_Playbook__c(RecordTypeId = rtTemplate.Id, Status__c = 'In Progress');
        insert playbookTemplate;
        
        Release_Playbook__c releasePlaybook = new Release_Playbook__c(RecordTypeId = rtReleasePlaybook.Id, Status__c = 'In Progress');
        insert releasePlaybook;
        
        Release_Playbook_Item__c itemTemplate = new Release_Playbook_Item__c(RecordTypeId = rtItemTemplate.Id, 
                                                                             Release_Playbook__c = playbookTemplate.Id,
                                                                             Area__c = 'Testing', End_Date_Time__c = DateTime.now(),
                                                                             Environment__c = 'UAT',
                                                                             Execution_Sequence__c = 'Deployment',
                                                                             Issues_Comments__c = 'None',
                                                                             Order__c = 1, Stage__c = 'Deployment',
                                                                             Start_Date_Time__c = DateTime.now(),
                                                                             Status__c = 'In Progress',
                                                                             Task_Description__c = 'Test Task');
        insert itemTemplate;
        
        Release_Assignment__c assignmentTemplate = new Release_Assignment__c(RecordTypeId = rtAssignment.Id,
                                                                             Release_Playbook__c = playbookTemplate.Id,
                                                                             Company__c = 'Test Company', Contact__c = 'Test Contact',
                                                                             Email__c = 'test@example.com',Role__c = 'DevOps');
        insert assignmentTemplate;
    }
    
    @isTest
    static void testGetTemplateRecs() {
        Test.startTest();
        List<ReleasePlaybookController.ReleasePlaybookWrapper> result = ReleasePlaybookController.getTemplateRecs();
        Test.stopTest();
        
        // Check Assertion results
        System.assertNotEquals(null, result, 'Result should not be null');
        System.assert(result.size() > 0, 'Result list should not be empty');
    }
    
    @isTest
    static void testCreateReleasePlaybookItems() {
        Id releasePlaybookId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook' LIMIT 1].Id;
        Id selectedTemplateId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook Template' LIMIT 1].Id;
        
        Test.startTest();
        try {
            ReleasePlaybookController.createReleasePlaybookItems(releasePlaybookId, selectedTemplateId);
        } catch (Exception e) {
            System.debug('Exception thrown: ' + e.getMessage());
            System.debug('Stack Trace: ' + e.getStackTraceString());
        }
        Test.stopTest();
        
        List<Release_Playbook_Item__c> items = [SELECT Id FROM Release_Playbook_Item__c WHERE Release_Playbook__c = :releasePlaybookId];
        List<Release_Assignment__c> assignments = [SELECT Id FROM Release_Assignment__c WHERE Release_Playbook__c = :releasePlaybookId];
        
        System.assert(items.size() > 0, 'There should be new Release Playbook Items created.');
        System.assert(assignments.size() > 0, 'There should be new Release Assignments created.');
    }
    
    @isTest
    static void testCreateReleasePlaybookItems_noTemplateId() {
        Id releasePlaybookId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook' LIMIT 1].Id;
        
        Test.startTest();
        try {
            ReleasePlaybookController.createReleasePlaybookItems(releasePlaybookId, null);
            System.assert(false, 'An exception should have been thrown.');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'Expected error message.');
        }
        Test.stopTest();
    }
    
    @isTest
    static void testCreateReleasePlaybookItems_itemsAlreadyExist() {
        Id releasePlaybookId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook' LIMIT 1].Id;
        Id selectedTemplateId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook Template' LIMIT 1].Id;
        
        // Insert an item to simulate existing items
        Release_Playbook_Item__c existingItem = new Release_Playbook_Item__c(Release_Playbook__c = releasePlaybookId, Area__c = 'Testing');
        insert existingItem;
        
        Test.startTest();
        try {
            ReleasePlaybookController.createReleasePlaybookItems(releasePlaybookId, selectedTemplateId);
            System.assert(false, 'An exception should have been thrown.');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'Expected error message.');
        }
        Test.stopTest();
    }
    
    @isTest
    static void testCreateReleasePlaybookItems_noChildTemplates() {
        Id releasePlaybookId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook' LIMIT 1].Id;
        Id selectedTemplateId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook Template' LIMIT 1].Id;
        
        // Remove child templates to simulate no child templates
        List<Release_Playbook_Item__c> childTemplates = [SELECT Id FROM Release_Playbook_Item__c WHERE Release_Playbook__c = :selectedTemplateId];
        delete childTemplates;
        
        Test.startTest();
        try {
            ReleasePlaybookController.createReleasePlaybookItems(releasePlaybookId, selectedTemplateId);
            System.assert(false, 'An exception should have been thrown.');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'Expected error message.');
        }
        Test.stopTest();
    }
    
    @isTest
    static void testCreateReleasePlaybookItems_noAssignments() {
        Id releasePlaybookId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook' LIMIT 1].Id;
        Id selectedTemplateId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook Template' LIMIT 1].Id;
        
        // Remove assignments to simulate no assignments
        List<Release_Assignment__c> assignments = [SELECT Id FROM Release_Assignment__c WHERE Release_Playbook__c = :selectedTemplateId];
        delete assignments;
        
        Test.startTest();
        try {
            ReleasePlaybookController.createReleasePlaybookItems(releasePlaybookId, selectedTemplateId);
        } catch (Exception e) {
            System.debug('Exception thrown: ' + e.getMessage());
            System.debug('Stack Trace: ' + e.getStackTraceString());
        }
        Test.stopTest();
        
        List<Release_Playbook_Item__c> items = [SELECT Id FROM Release_Playbook_Item__c WHERE Release_Playbook__c = :releasePlaybookId];
        List<Release_Assignment__c> newAssignments = [SELECT Id FROM Release_Assignment__c WHERE Release_Playbook__c = :releasePlaybookId];
        
        System.assert(items.size() > 0, 'There should be new Release Playbook Items created.');
        System.assertEquals(0, newAssignments.size(), 'There should be no new Release Assignments created.');
    }
    
    @isTest
    static void testCreateReleasePlaybookItems_InvalidTemplateId() {
        Id releasePlaybookId = [SELECT Id FROM Release_Playbook__c WHERE RecordType.Name = 'Release Playbook' LIMIT 1].Id;
        Id invalidTemplateId = 'a2g7d000002aryXAAQ';
        
        Test.startTest();
        try {
            ReleasePlaybookController.createReleasePlaybookItems(releasePlaybookId, invalidTemplateId);
            System.assert(false, 'An exception should have been thrown.');
        } catch (AuraHandledException e) {
            System.assert(e.getMessage().contains('Script-thrown exception'), 'Expected error message.');
        }
        Test.stopTest();
    }
    
}