force-app/main/default/objects/copado__User_Story__c/fields/Jira_Key__c.field-meta.xml
<CustomField>
    <fullName>Jira_Key__c</fullName>
    <label>Jira Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/Issue_Tracker__c.object-meta.xml
<CustomObject>
    <description>This object is used for Copado Issues Tracking for Dev and DevOps</description>
    <label>Issue Tracker</label>
    <nameField>
        <displayFormat>IT-{000000}</displayFormat>
        <label>Issue Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Tracker__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Please provide the category of the Issue.</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code Override</fullName>
            </value>
            <value>
                <fullName>Commit Issue</fullName>
            </value>
            <value>
                <fullName>Merge Issue</fullName>
            </value>
            <value>
                <fullName>Developer Support</fullName>
            </value>
            <value>
                <fullName>Environment Issue</fullName>
            </value>
            <value>
                <fullName>Deployment Issue</fullName>
            </value>
            <value>
                <fullName>Tooling</fullName>
            </value>
            <value>
                <fullName>OmniStudio Issue</fullName>
            </value>
            <value>
                <fullName>User Setup</fullName>
            </value>
            <value>
                <fullName>User Creation</fullName>
            </value>
            <value>
                <fullName>Knowledge Issue</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Developer__c.field-meta.xml
<CustomField>
    <fullName>Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please provide the Developer Name.</inlineHelpText>
    <label>Developer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Developer</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Issue_Description__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description__c</fullName>
    <label>Issue Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Issue_Environment__c.field-meta.xml
<CustomField>
    <fullName>Issue_Environment__c</fullName>
    <inlineHelpText>Please select the environment to which the issue is applicable.</inlineHelpText>
    <label>Issue Environment</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Environments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/JIRA_Key__c.field-meta.xml
<CustomField>
    <fullName>JIRA_Key__c</fullName>
    <inlineHelpText>Please provide the JIRA Key associated to the defect/issue.</inlineHelpText>
    <label>JIRA Key</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Other_Information__c.field-meta.xml
<CustomField>
    <fullName>Other_Information__c</fullName>
    <inlineHelpText>Please update this field id the category is set to other.</inlineHelpText>
    <label>Other Information</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Provide the Issue Priority.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
            </value>
            <value>
                <fullName>P5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Looking into Issue</fullName>
            </value>
            <value>
                <fullName>Need Additional Information</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Track in Higher Org</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/User_Story_Impacted__c.field-meta.xml
<CustomField>
    <fullName>User_Story_Impacted__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please provide the associated User Story impacted by the issue.</inlineHelpText>
    <label>User Story Impacted</label>
    <referenceTo>copado__User_Story__c</referenceTo>
    <relationshipLabel>Issue Tracker</relationshipLabel>
    <relationshipName>Issue_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/recordTypes/Rollback_Request.recordType-meta.xml
<RecordType>
    <fullName>Rollback_Request</fullName>
    <active>true</active>
    <label>Rollback Request</label>
</RecordType>

force-app/main/default/globalValueSets/Environments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DEV</fullName>
    </customValue>
    <customValue>
        <fullName>INT</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <customValue>
        <fullName>UAT2</fullName>
    </customValue>
    <customValue>
        <fullName>PreProd</fullName>
    </customValue>
    <customValue>
        <fullName>PROD</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>ScaleTest</fullName>
    </customValue>
    <masterLabel>Environments</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/usdependencyhandler.cls
public with sharing class usdependencyhandler {
    private static Boolean isExecuting = false;
    
    public static void updatestatus(Set<Id> updatedUserStoryIds) {
        // Check if already executing
        if(isExecuting) return;
        
        try {
            isExecuting = true;
            
            // Query to get all User Stories with Ids in the set 'updatedUserStoryIds'
            List<copado__User_Story__c> userStories = [SELECT Id, copado__Status__c 
                                                      FROM copado__User_Story__c 
                                                      WHERE Id IN :updatedUserStoryIds];
            
            // Create a map to store the status of each user story
            Map<Id, String> userStoryStatusMap = new Map<Id, String>();
            for (copado__User_Story__c userStory : userStories) {
                userStoryStatusMap.put(userStory.Id, userStory.copado__Status__c);
            }
            
            // Query dependent user stories
            List<copado__Team_Dependency__c> dependencies = [SELECT Id, copado__Dependent_User_Story__c, copado__Provider_User_Story__c 
                                                           FROM copado__Team_Dependency__c 
                                                           WHERE copado__Provider_User_Story__c IN :updatedUserStoryIds];
            
            // Collect dependent user story IDs
            Set<Id> dependentUserStoryIds = new Set<Id>();
            Map<Id, Id> dependencyMap = new Map<Id, Id>();
            for (copado__Team_Dependency__c dependency : dependencies) {
                dependentUserStoryIds.add(dependency.copado__Dependent_User_Story__c);
                dependencyMap.put(dependency.copado__Dependent_User_Story__c, dependency.copado__Provider_User_Story__c);
            }
            
            // Query dependent user stories to update
            List<copado__User_Story__c> dependentUserStories = [SELECT Id, copado__Status__c 
                                                               FROM copado__User_Story__c 
                                                               WHERE Id IN :dependentUserStoryIds];
            
            // Create a list to store the dependent user stories that need to be updated
            List<copado__User_Story__c> storiesToUpdate = new List<copado__User_Story__c>();
            
            // Update the status of the dependent user stories
            for (copado__User_Story__c dependentUserStory : dependentUserStories) {
                Id providerUserStoryId = dependencyMap.get(dependentUserStory.Id);
                if (userStoryStatusMap.containsKey(providerUserStoryId)) {
                    dependentUserStory.copado__Status__c = userStoryStatusMap.get(providerUserStoryId);
                    storiesToUpdate.add(dependentUserStory);
                }
            }
            
            // Perform DML operation to update the dependent user stories
            if (!storiesToUpdate.isEmpty()) {
                update storiesToUpdate;
            }
        } catch(Exception e) {
            System.debug('Error in updatestatus: ' + e.getMessage());
            throw e;
        } finally {
            isExecuting = false;
        }
    }  
    
    public static void createRollbackRequests(List<copado__User_Story__c> cancelledUserStories) {
        try {
            // Retrieve environment records dynamically
            Map<String, String> environmentMapping = new Map<String, String>();
            // Query the object where CFEC__Type__c field resides
            // Commneted tyep filed CFEC__Type__c
            List<copado__Environment__c> environmentRecords = [SELECT Id, Name, Type__c 
                                                             FROM copado__Environment__c 
                                                             WHERE Type__c != null];
            
            // Populate the map with environment name and CFEC__Type__c value
            // Commneted tyep filed CFEC__Type__c
            for (copado__Environment__c env : environmentRecords) {
                environmentMapping.put(env.Name, env.Type__c);
            }
            System.debug('environmentMapping ==> '+ environmentMapping);
            
            System.debug('cancelledUserStories ==> '+ cancelledUserStories);
            
            // Collect IDs of cancelled user stories
            Set<Id> cancelledUserStoryIds = new Set<Id>();
            for (copado__User_Story__c userStory : cancelledUserStories) {
                if (userStory.copado__Status__c == 'Cancelled') {
                    cancelledUserStoryIds.add(userStory.Id);
                }
            }
            if (cancelledUserStoryIds.isEmpty()) return;
            
            // Retrieve user story details into a map
            Map<Id, copado__User_Story__c> userStoryMap = new Map<Id, copado__User_Story__c>(
                [SELECT Id, copado__Environment__c, copado__User_Story_Title__c, Name, 
                 copado__Developer__c, Jira_Key__c 
                 FROM copado__User_Story__c
                 WHERE Id IN :cancelledUserStoryIds]);
            
            // Retrieve active promoted user stories via the junction object
            List<copado__Promoted_User_Story__c> promotedUserStories = [SELECT Id, copado__Promotion__c, copado__User_Story__c 
                                                                       FROM copado__Promoted_User_Story__c 
                                                                       WHERE copado__User_Story__c IN :cancelledUserStoryIds];
            
            System.debug('promotedUserStories ==> '+ promotedUserStories);
            
            // Collect promotion IDs from the junction object
            Set<Id> promotionIds = new Set<Id>();
            for (copado__Promoted_User_Story__c promotedUserStory : promotedUserStories) {
                if (promotedUserStory.copado__Promotion__c != null) {
                    promotionIds.add(promotedUserStory.copado__Promotion__c);
                }
            }
            if (promotionIds.isEmpty()) return;
            
            // Retrieve completed promotion records
            List<copado__Promotion__c> completedPromotions = [SELECT Id, copado__Source_Environment__c, copado__Destination_Environment__c
                                                            FROM copado__Promotion__c 
                                                            WHERE Id IN :promotionIds 
                                                            AND copado__Status__c = 'Completed'];
            
            System.debug('completedPromotions ==> '+ completedPromotions);
            
            // Query environments to map Ids to names
            Set<Id> environmentIds = new Set<Id>();
            for (copado__Promotion__c promotion : completedPromotions) {
                if (promotion.copado__Source_Environment__c != null) {
                    environmentIds.add(promotion.copado__Source_Environment__c);
                }
                if (promotion.copado__Destination_Environment__c != null) {
                    environmentIds.add(promotion.copado__Destination_Environment__c);
                }
            }
            // Commneted tyep filed CFEC__Type__c
            Map<Id, String> environmentIdToNameMap = new Map<Id, String>();
            if (!environmentIds.isEmpty()) {
                List<copado__Environment__c> environments = [SELECT Id, Name, copado__Type__c, Type__c 
                                                           FROM copado__Environment__c 
                                                           WHERE Id IN :environmentIds];
                for (copado__Environment__c environment : environments) {
                    environmentIdToNameMap.put(environment.Id, environment.Name);
                }
            }
            System.debug('environmentIdToNameMap ==> '+ environmentIdToNameMap);
            
            // Translate environment Ids to names and store in uniqueGlobalEnvironments
            Map<Id, Set<String>> userStoryToEnvironments = new Map<Id, Set<String>>();
            for (copado__Promotion__c promotion : completedPromotions) {
                if (promotion.copado__Source_Environment__c != null) {
                    String sourceEnv = environmentIdToNameMap.get(promotion.copado__Source_Environment__c);
                    if (sourceEnv != null) {
                        for (copado__Promoted_User_Story__c promotedUserStory : promotedUserStories) {
                            if (!userStoryToEnvironments.containsKey(promotedUserStory.copado__User_Story__c)) {
                                userStoryToEnvironments.put(promotedUserStory.copado__User_Story__c, new Set<String>());
                            }
                            userStoryToEnvironments.get(promotedUserStory.copado__User_Story__c).add(sourceEnv);
                        }
                    }
                }
                if (promotion.copado__Destination_Environment__c != null) {
                    String destEnv = environmentIdToNameMap.get(promotion.copado__Destination_Environment__c);
                    if (destEnv != null) {
                        for (copado__Promoted_User_Story__c promotedUserStory : promotedUserStories) {
                            if (!userStoryToEnvironments.containsKey(promotedUserStory.copado__User_Story__c)) {
                                userStoryToEnvironments.put(promotedUserStory.copado__User_Story__c, new Set<String>());
                            }
                            userStoryToEnvironments.get(promotedUserStory.copado__User_Story__c).add(destEnv);
                        }
                    }
                }
            }
            
            // Fetch the Rollback Request record type ID
            Id rollbackRequestRecordTypeId = [SELECT Id 
                                            FROM RecordType 
                                            WHERE SObjectType = 'Issue_Tracker__c' 
                                            AND DeveloperName = 'Rollback_Request' 
                                            LIMIT 1].Id;
            
            // Create rollback requests
            List<Issue_Tracker__c> rollbackRequests = new List<Issue_Tracker__c>();
            
            // Iterate over cancelled user stories and their environments
            for (Id userStoryId : cancelledUserStoryIds) {
                if (userStoryToEnvironments.containsKey(userStoryId)) {
                    Set<String> environments = userStoryToEnvironments.get(userStoryId);
                    List<String> mappedEnvironments = new List<String>();
                    for (String environment : environments) {
                        String mappedEnvironment = environmentMapping.get(environment);
                        if (mappedEnvironment != null) {
                            mappedEnvironments.add(mappedEnvironment);
                        }
                    }
                    
                    String concatenatedEnvironments = String.join(mappedEnvironments, '; ');
                    
                    System.debug('concatenatedEnvironments ==> '+ concatenatedEnvironments);
                    
                    if (!mappedEnvironments.isEmpty()) {
                        copado__User_Story__c userStory = userStoryMap.get(userStoryId);
                        rollbackRequests.add(new Issue_Tracker__c(
                            Issue_Description__c = 'Rollback Request: ' + userStory.copado__User_Story_Title__c,
                            Issue_Environment__c = concatenatedEnvironments,
                            Status__c = 'New',
                            Category__c = 'Other',
                            Other_Information__c = 'Jira cancelled and no requirement needed as for now',
                            Priority__c = 'P3',
                            Developer__c = userStory.copado__Developer__c,
                            User_Story_Impacted__c = userStory.Id,
                            JIRA_Key__c = userStory.Jira_Key__c,
                            RecordTypeId = rollbackRequestRecordTypeId
                        ));
                    }
                }
            }
            
            // Insert rollback requests
            if (!rollbackRequests.isEmpty()) {
                insert rollbackRequests;
                System.debug('rollbackRequests ==> '+ rollbackRequests);
            }
        } catch(Exception e) {
            System.debug('Error in createRollbackRequests: ' + e.getMessage());
            throw e;
        }
    }    
}