force-app/main/default/objects/Audit_Log_Report__c/Audit_Log_Report__c.object-meta.xml
<CustomObject>
    <label>Audit Log Report</label>
    <nameField>
        <displayFormat>ALR-{00000}</displayFormat>
        <label>Audit Log Report Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit Log Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log_Report__c/fields/Delegate_User__c.field-meta.xml
<CustomField>
    <fullName>Delegate_User__c</fullName>
    <inlineHelpText>The Login-As user who executed the action in Setup.</inlineHelpText>
    <label>Delegate User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Report__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <inlineHelpText>The full description of changes made in Setup</inlineHelpText>
    <label>Display</label>
    <length>50768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Report__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>The section in the Setup menu where the action occurred</inlineHelpText>
    <label>Section</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuditLogReport.cls
public class AuditLogReport {

    public static void createAuditLogReports() {
        
    	List<Audit_Log_Report__c> auditLogReportsToInsert = new List<Audit_Log_Report__c>();
    
        // Query the data from SetupAuditTrail
        List<SetupAuditTrail> auditTrailRecords = [SELECT Id, CreatedDate, CreatedBy.Name, Section, Action, DelegateUser, Display
                                                        FROM SetupAuditTrail
                                                        WHERE CreatedDate = LAST_N_DAYS:7];
    
        // Loop through the queried records and create Audit Log Report records
        for (SetupAuditTrail auditTrailRecord : auditTrailRecords){
            
        	Audit_Log_Report__c auditLogReport = new Audit_Log_Report__c();
            
            auditLogReport.Date__c = auditTrailRecord.CreatedDate;
            auditLogReport.User__c = auditTrailRecord.CreatedBy.Name;
            auditLogReport.Section__c = auditTrailRecord.Section;
            auditLogReport.Delegate_User__c = auditTrailRecord.DelegateUser;
            auditLogReport.Display__c = auditTrailRecord.Display;
                
            auditLogReportsToInsert.add(auditLogReport);
        }
    	
        // Insert the Audit Log Report records
        if (!auditLogReportsToInsert.isEmpty()) {
            Database.insert(auditLogReportsToInsert, false);
       	}
        
	}

}