force-app/main/default/objects/PR_Event__e/PR_Event__e.object-meta.xml
<CustomObject>
    <label>PR Event</label>
    <pluralLabel>PR Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pull_Request_Event__c/Pull_Request_Event__c.object-meta.xml
<CustomObject>
    <label>Pull Request Event</label>
    <nameField>
        <label>Pull Request Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pull Request Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pull_Request_Event__c/fields/Entire_Payload__c.field-meta.xml
<CustomField>
    <fullName>Entire_Payload__c</fullName>
    <label>Entire Payload</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Event__c/fields/event_type__c.field-meta.xml
<CustomField>
    <fullName>event_type__c</fullName>
    <label>event type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/webhooksubscription.cls
@RestResource(urlMapping='/api/webhooks/pushDetails/*')
global without sharing class webhooksubscription {
    @HttpPost
    global static void handleNotification() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        try{
            
            System.debug(request.requestURI);
            System.debug(request.requestBody.toString());
            
            String jsonString = request.requestBody.toString();
            Map<String, Object> payload = (Map<String, Object>) JSON.deserializeUntyped(jsonString);
            
            // Create a new record in the custom object
            Pull_Request_Event__c event = new Pull_Request_Event__c();
            event.Entire_Payload__c = jsonString;  // Store the entire payload as a string, if needed
            event.Event_Type__c =payload.get('action').toString();
            insert event;
            String eventType = String.valueOf(payload.get('action'));

            // Publish Platform Event
            PR_Event__e pe = new PR_Event__e(
                Event_Type__c = eventType,
                Payload__c = jsonString
            );
            EventBus.publish(pe);

            response.statusCode = 200;
            response.responseBody = Blob.valueOf('{"status": "Platform Event published successfully"}');  
        }
        catch(Exception e){
            System.debug('exception +++'+ e.getMessage());
            response.statusCode = 200;
                response.responseBody = Blob.valueOf('{"status":'+ e.getMessage()+'=='+e.getLineNumber()+'}');
        }
    }
}