force-app/main/default/objects/Issue_Tracker__c/Issue_Tracker__c.object-meta.xml
<CustomObject>
    <description>This object is used for Copado Issues Tracking for Dev and DevOps</description>
    <label>Issue Tracker</label>
    <nameField>
        <displayFormat>IT-{000000}</displayFormat>
        <label>Issue Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issue Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue_Tracker__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Please provide the category of the Issue.</inlineHelpText>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Code Override</fullName>
            </value>
            <value>
                <fullName>Commit Issue</fullName>
            </value>
            <value>
                <fullName>Merge Issue</fullName>
            </value>
            <value>
                <fullName>Developer Support</fullName>
            </value>
            <value>
                <fullName>Environment Issue</fullName>
            </value>
            <value>
                <fullName>Deployment Issue</fullName>
            </value>
            <value>
                <fullName>Tooling</fullName>
            </value>
            <value>
                <fullName>OmniStudio Issue</fullName>
            </value>
            <value>
                <fullName>User Setup</fullName>
            </value>
            <value>
                <fullName>User Creation</fullName>
            </value>
            <value>
                <fullName>Knowledge Issue</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Issue_Description__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description__c</fullName>
    <label>Issue Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Issue_Environment__c.field-meta.xml
<CustomField>
    <fullName>Issue_Environment__c</fullName>
    <inlineHelpText>Please select the environment to which the issue is applicable.</inlineHelpText>
    <label>Issue Environment</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Environments</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <inlineHelpText>Provide the Issue Priority.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>P4</fullName>
            </value>
            <value>
                <fullName>P5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue_Tracker__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>copado__Team__c</referenceTo>
    <relationshipLabel>Issue Tracker</relationshipLabel>
    <relationshipName>Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>Users team name.</description>
    <inlineHelpText>Name of the team that user belongs to</inlineHelpText>
    <label>Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CloudFulcrum Team</fullName>
            </value>
            <value>
                <fullName>Financial Service Team</fullName>
            </value>
            <value>
                <fullName>Service Team</fullName>
            </value>
            <value>
                <fullName>Salesforce Automated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/User_Access_Managment__c.object-meta.xml
<CustomObject>
    <description>Object to Request user access to salesforce environments</description>
    <label>User Access Managment</label>
    <nameField>
        <displayFormat>UAR - {0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Access Managments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Access_Managment__c/fields/Divsion__c.field-meta.xml
<CustomField>
    <fullName>Divsion__c</fullName>
    <label>Division</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>QE</fullName>
            </value>
            <value>
                <fullName>Product/Business</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Environments__c.field-meta.xml
<CustomField>
    <fullName>Environments__c</fullName>
    <label>Environments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC Dev1</fullName>
            </value>
            <value>
                <fullName>BRO</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>FSC INT</fullName>
            </value>
            <value>
                <fullName>FSC QA</fullName>
            </value>
            <value>
                <fullName>FSC UAT</fullName>
            </value>
            <value>
                <fullName>FSC PREPROD</fullName>
            </value>
            <value>
                <fullName>POC DEV1</fullName>
            </value>
            <value>
                <fullName>BRP POC</fullName>
                <isActive>false</isActive>
                <label>BRP POC</label>
            </value>
            <value>
                <fullName>EDJ GOV</fullName>
                <isActive>false</isActive>
                <label>EDJ GOV</label>
            </value>
            <value>
                <fullName>FSC SCALETEST</fullName>
                <isActive>false</isActive>
                <label>FSC SCALETEST</label>
            </value>
            <value>
                <fullName>Pioneer POC</fullName>
                <isActive>false</isActive>
                <label>Pioneer POC</label>
            </value>
            <value>
                <fullName>Training Org</fullName>
                <isActive>false</isActive>
                <label>Training Org</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <inlineHelpText>Comprising permission set, profile, permission set group, and territory</inlineHelpText>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financial Advisor (FA)</fullName>
            </value>
            <value>
                <fullName>Branch Office Administrator (BOA)</fullName>
            </value>
            <value>
                <fullName>Home Office 1</fullName>
            </value>
            <value>
                <fullName>Legal/Field Supervision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>HQIS</fullName>
                <isActive>false</isActive>
                <label>HQIS</label>
            </value>
            <value>
                <fullName>Home Office 2</fullName>
                <isActive>false</isActive>
                <label>Home Office 2</label>
            </value>
            <value>
                <fullName>System Admin Read Only</fullName>
                <isActive>false</isActive>
                <label>System Admin Read Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Product_Team__c.field-meta.xml
<CustomField>
    <fullName>Product_Team__c</fullName>
    <label>Product Team</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New User Request</fullName>
            </value>
            <value>
                <fullName>Existing User Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Start_Of_Day__c.field-meta.xml
<CustomField>
    <fullName>Start_Of_Day__c</fullName>
    <defaultValue>TEXT(TIMEVALUE(&apos;01:00&apos;))</defaultValue>
    <label>Start Of Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Access_Managment__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone fo the user</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+05:30) India Standard Time (Asia/Kolkata)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:30) Newfoundland Standard Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-02:30) Newfoundland Daylight Time (America/St_Johns)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Atlantic Standard Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-03:00) Atlantic Daylight Time (America/Halifax)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Detroit)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Eastern Standard Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-04:00) Eastern Daylight Time (America/Toronto)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Chicago)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Central Standard Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-05:00) Central Daylight Time (America/Winnipeg)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Denver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Mountain Standard Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-06:00) Mountain Daylight Time (America/Edmonton)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Los_Angeles)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Pacific Standard Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-07:00) Pacific Daylight Time (America/Vancouver)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Alaska Standard Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-08:00) Alaska Daylight Time (America/Anchorage)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-09:00) Hawaii-Aleutian Daylight Time (America/Adak)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Honolulu)</fullName>
            </value>
            <value>
                <fullName>(GMT-10:00) Hawaii-Aleutian Standard Time (Pacific/Johnston)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UserAccessUpdateEvent__e/UserAccessUpdateEvent__e.object-meta.xml
<CustomObject>
    <label>UserAccessUpdateEvent</label>
    <pluralLabel>UserAccessUpdateEvents</pluralLabel>
</CustomObject>

force-app/main/default/objects/UserAccessUpdateEvent__e/fields/Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Update_Status__c</fullName>
    <label>Update Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Environments.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DEV</fullName>
    </customValue>
    <customValue>
        <fullName>INT</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <customValue>
        <fullName>UAT2</fullName>
    </customValue>
    <customValue>
        <fullName>PreProd</fullName>
    </customValue>
    <customValue>
        <fullName>PROD</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>ScaleTest</fullName>
    </customValue>
    <masterLabel>Environments</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>00:00</fullName>
    </customValue>
    <customValue>
        <fullName>01:00</fullName>
    </customValue>
    <customValue>
        <fullName>02:00</fullName>
    </customValue>
    <customValue>
        <fullName>03:00</fullName>
    </customValue>
    <customValue>
        <fullName>04:00</fullName>
    </customValue>
    <customValue>
        <fullName>05:00</fullName>
    </customValue>
    <customValue>
        <fullName>06:00</fullName>
    </customValue>
    <customValue>
        <fullName>07:00</fullName>
    </customValue>
    <customValue>
        <fullName>08:00</fullName>
    </customValue>
    <customValue>
        <fullName>09:00</fullName>
    </customValue>
    <customValue>
        <fullName>10:00</fullName>
    </customValue>
    <customValue>
        <fullName>11:00</fullName>
    </customValue>
    <customValue>
        <fullName>12:00</fullName>
    </customValue>
    <customValue>
        <fullName>13:00</fullName>
    </customValue>
    <customValue>
        <fullName>14:00</fullName>
    </customValue>
    <customValue>
        <fullName>15:00</fullName>
    </customValue>
    <customValue>
        <fullName>16:00</fullName>
    </customValue>
    <customValue>
        <fullName>17:00</fullName>
    </customValue>
    <customValue>
        <fullName>18:00</fullName>
    </customValue>
    <customValue>
        <fullName>19:00</fullName>
    </customValue>
    <customValue>
        <fullName>20:00</fullName>
    </customValue>
    <customValue>
        <fullName>21:00</fullName>
    </customValue>
    <customValue>
        <fullName>22:00</fullName>
    </customValue>
    <customValue>
        <fullName>23:00</fullName>
    </customValue>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UserAccessManagementController.cls
public without sharing class UserAccessManagementController {
    //User Access Management
    @AuraEnabled
    public static String createUserAccessRecord(User_Access_Managment__c objUser, string userType) {
        try {
            objUser.Request_Type__c= userType;
            System.debug('User type==> '+ objUser.Request_Type__c);
            System.debug('User Access: ' + objUser);
            insert objUser;
            objUser = [SELECT Name FROM User_Access_Managment__c WHERE Id = :objUser.Id LIMIT 1];
            return objUser.Name;
        } catch (Exception e) {
            // Log the error and return the error message
            System.debug('Error creating User Access Management record: ' + e.getMessage());
            return 'Error: ' + e.getMessage();
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getPersonaPicklistValues() {
        return getPicklistValues(User_Access_Managment__c.Persona__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getStartOfDayPicklistValues() {
        return getPicklistValues(User_Access_Managment__c.Start_Of_Day__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getProductTeamPicklistValues() {
        return getPicklistValues(User_Access_Managment__c.Product_Team__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getDivisionPicklistValues() {
        return getPicklistValues(User_Access_Managment__c.Divsion__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getTimeZonePicklistValues() {
        return getPicklistValues(User_Access_Managment__c.Time_Zone__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getEnvPicklistValues() {
        return getPicklistValues(User_Access_Managment__c.Environments__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<User> searchUsers(String searchTerm) {
        // Query users based on the search term
        String searchString = searchTerm + '%';
        return [SELECT Id, Name FROM User WHERE Name LIKE :searchString LIMIT 10];
    }
    
/*    //Issue Tracker
    @AuraEnabled
    public static String createIssueTrackerRecord(Issue_Tracker__c issueObj) {
        // Validate Access Details__c
        try {
            System.debug('User Access: ' + issueObj);
            insert issueObj;
            issueObj = [SELECT Issue_Description__c, Issue_Environment__c, Priority__c, Category__c, Team__r.Name 
                        FROM Issue_Tracker__c WHERE Id = :issueObj.Id LIMIT 1];
            return 'success';
            //   return issueObj.Name;
        } catch (Exception e) {
            // Log the error and return the error message
            System.debug('Error creating Issue Trcaker record: ' + e.getMessage());
            return 'Error: ' + e.getMessage();
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<IdNameWrapper> getTeams() {
        List<IdNameWrapper> teamOptions = new List<IdNameWrapper>();
        for (copado__Team__c team : [SELECT Id, Name FROM copado__Team__c]) {
            teamOptions.add(new IdNameWrapper(team.Id, team.Name));
        }
        return teamOptions;
    }
    
    public class IdNameWrapper {
        @AuraEnabled public Id id;
        @AuraEnabled public String name;
        public IdNameWrapper(Id id, String name) {
            this.id = id;
            this.name = name;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getCategoryPicklistValues() {
        return getPicklistValues(Issue_Tracker__c.Category__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getPriorityPicklistValues() {
        return getPicklistValues(Issue_Tracker__c.Priority__c);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getEnvironmentPicklistValues() {
        return getPicklistValues(Issue_Tracker__c.Issue_Environment__c);
    } 
*/  
    
    private static List<String> getPicklistValues(Schema.SObjectField field) {
        List<String> picklistValues = new List<String>();
        Schema.DescribeFieldResult fieldResult = field.getDescribe();
        List<Schema.PicklistEntry> picklistEntries = fieldResult.getPicklistValues();
        
        for (Schema.PicklistEntry entry : picklistEntries) {
            picklistValues.add(entry.getLabel());
        }
        
        return picklistValues;
    }

	public static void publishAccessUpdateEvent(Id recordId) {
        List<UserAccessUpdateEvent__e> eventList = new List<UserAccessUpdateEvent__e>();
		eventList.add(new UserAccessUpdateEvent__e(Record_Id__c = recordId, Update_Status__c = 'Approved') );
		eventList.add(new UserAccessUpdateEvent__e(Record_Id__c = recordId, Update_Status__c = 'Approved') );

        List<Database.SaveResult> resultList = EventBus.publish(eventList);
        for(Database.SaveResult result: resultList){
            if (result.isSuccess()) {
                System.debug('Platform Event publish successfully: ');
            }  
            else {
                List<Database.error> errList = result.getErrors();
                for(Database.error err: errList){
                	System.debug('Failed to publish platform event: ' +err.getMessage());
                }
            }  
        }
    } 
}