force-app/main/default/objects/Release_Playbook__c/Release_Playbook__c.object-meta.xml
<CustomObject>
    <label>Release Playbook</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Release Playbook Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>copado__Deployment_Flow__c</referenceTo>
    <relationshipLabel>Release Playbooks</relationshipLabel>
    <relationshipName>Release_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/fields/Release_Template__c.field-meta.xml
<CustomField>
    <fullName>Release_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Template</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Playbooks</relationshipLabel>
    <relationshipName>Release_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/Release_Playbook_Item__c.object-meta.xml
<CustomObject>
    <label>Release Playbook Item</label>
    <nameField>
        <displayFormat>RPI-{000000}</displayFormat>
        <label>Release Playbook Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbook Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Execution_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Execution_Sequence__c</fullName>
    <label>Execution Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before Deployment</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>After Deployment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>copado__Deployment_Flow__c</referenceTo>
    <relationshipLabel>Release Playbook Items</relationshipLabel>
    <relationshipName>Release_Playbook_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Playbook Items</relationshipLabel>
    <relationshipName>Release_Playbook_Items1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/SCA__c.field-meta.xml
<CustomField>
    <fullName>SCA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Sub_Item__c/Release_Playbook_Sub_Item__c.object-meta.xml
<CustomObject>
    <label>Release Playbook Sub Item</label>
    <nameField>
        <displayFormat>RPSI-{000000}</displayFormat>
        <label>Release Playbook Sub Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbook Sub Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook_Sub_Item__c/fields/Previous_SCA__c.field-meta.xml
<CustomField>
    <fullName>Previous_SCA__c</fullName>
    <label>Previous SCA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Sub_Item__c/fields/Release_Playbook_Item__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook_Item__c</fullName>
    <label>Release Playbook Item</label>
    <referenceTo>Release_Playbook_Item__c</referenceTo>
    <relationshipLabel>Release Playbook Sub Items</relationshipLabel>
    <relationshipName>Release_Playbook_Sub_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Sub_Item__c/fields/SCA_Execution_Time__c.field-meta.xml
<CustomField>
    <fullName>SCA_Execution_Time__c</fullName>
    <label>SCA Execution Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Sub_Item__c/fields/Static_Code_Analysis_Result__c.field-meta.xml
<CustomField>
    <fullName>Static_Code_Analysis_Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Static Code Analysis Result</label>
    <referenceTo>copado__Static_Code_Analysis_Result__c</referenceTo>
    <relationshipLabel>Release Playbook Sub Items</relationshipLabel>
    <relationshipName>Release_Playbook_Sub_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SCAScanHandlerTest.cls
@IsTest
public class SCAScanHandlerTest {
    
    @TestSetup
    static void setupTestData() {       
        Id trnProdOrgId = Label.Prod_Credential;
        System.debug('TrnOrg Id: +++ ' + trnProdOrgId);
        
        // Create a test Org record
        copado__Org__c testOrg = new copado__Org__c(Name = 'trnProd');
        insert testOrg;
        System.debug('Test Org: +++++ ' + testOrg);
        
        // Create a Copado Deployment Flow (Pipeline)
        copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(
            Name = 'Test Pipeline', copado__Active__c = true, copado__Platform__c = 'Other');
        insert pipeline;
        
        // Create a Release Playbook Template
        Release_Playbook__c templateRP = new Release_Playbook__c(Pipeline__c = pipeline.Id);
        insert templateRP;
        
        // Create a Release Playbook record
        Release_Playbook__c playbook = new Release_Playbook__c(Pipeline__c = pipeline.Id, Release_Template__c = templateRP.Id);
        insert playbook;
        System.debug('PlayBook: +++++ ' + playbook);
        
        // Create related Release Playbook Items with SCA__c set to true
        Release_Playbook_Item__c playbookItem = new Release_Playbook_Item__c(
            Release_Playbook__c = playbook.Id, SCA__c = true, Execution_Sequence__c = 'Before Deployment'); 
        insert playbookItem;
        System.debug('PlayBook Item: +++++ ' + playbookItem);
        
        // Create first SCA Result record
        copado__Static_Code_Analysis_Result__c result1 = new copado__Static_Code_Analysis_Result__c(
            copado__Org_Credential__c = trnProdOrgId);
        insert result1;
        System.debug('SCA Result 1: ++++ ' + result1);
        
        // Fetch SCA Result Records
        copado__Static_Code_Analysis_Result__c res1 = [SELECT Id, Name FROM copado__Static_Code_Analysis_Result__c WHERE id = :result1.Id];
        System.debug('Result Name ++++' +  res1);
        
        // Create a Release Playbook Sub Item
        Release_Playbook_Sub_Item__c subItem = new Release_Playbook_Sub_Item__c(
            Release_Playbook_Item__c = playbookItem.Id, Previous_SCA__c = res1.Name, Static_Code_Analysis_Result__c = result1.Id);
        insert subItem;
        System.debug('subItem: +++++ ' + subItem);
    }
    
    @IsTest
    static void testHandleAfterInsert_SuccessScenario() {
        // Get the test data
        Id trnProdOrgId = Label.Prod_Credential;
        System.debug('Get TrnOrg Id: +++ ' + trnProdOrgId);
        
        // Query existing SCA results
        copado__Static_Code_Analysis_Result__c existingResult = [SELECT Id, Name FROM copado__Static_Code_Analysis_Result__c 
                                                                 WHERE copado__Org_Credential__c = :trnProdOrgId LIMIT 1];
        System.debug('Existing Results : ++++ ' + existingResult);
        
        // Get the existing sub item
        Release_Playbook_Sub_Item__c existingSubItem = [SELECT Id, Previous_SCA__c FROM Release_Playbook_Sub_Item__c 
                                                        WHERE Previous_SCA__c = :existingResult.Name LIMIT 1];
		System.debug('Exixsting Sub Item: +++' + existingSubItem);
        
        Test.startTest();        
        copado__Static_Code_Analysis_Result__c newResult = new copado__Static_Code_Analysis_Result__c(
            copado__Org_Credential__c = trnProdOrgId);
        insert newResult;        
        Test.stopTest();
        
        // Verify the Release Playbook Sub Item was updated
        Release_Playbook_Sub_Item__c updatedSubItem = [SELECT Id, Static_Code_Analysis_Result__c, SCA_Execution_Time__c 
                                                       FROM Release_Playbook_Sub_Item__c WHERE Id = :existingSubItem.Id];
        System.debug('Updated SubItems : ++++ ' + updatedSubItem);
        System.assertEquals(newResult.Id, updatedSubItem.Static_Code_Analysis_Result__c, 'The Sub Item should be updated with the new SCA Result Id');
        System.assertNotEquals(null, updatedSubItem.SCA_Execution_Time__c, 'Execution time should be populated');
    }
    
    @IsTest
    static void testHandleAfterInsert_InvalidOrgId() {
        // Test scenario where Org Id is invalid
        Test.startTest();        
        copado__Static_Code_Analysis_Result__c invalidResult = new copado__Static_Code_Analysis_Result__c();
        insert invalidResult;        
        Test.stopTest();
        
        System.assert(true, 'Should handle invalid Org Id gracefully');
    }
    
    @IsTest
    static void testHandleAfterInsert_NoMatchingSubItem() {
        // Delete existing Release Playbook Sub Items
        delete [SELECT Id FROM Release_Playbook_Sub_Item__c];        
        Id trnProdOrgId = Label.Prod_Credential;
        
        Test.startTest();        
        copado__Static_Code_Analysis_Result__c newResult = new copado__Static_Code_Analysis_Result__c(
            copado__Org_Credential__c = trnProdOrgId);
        insert newResult;       
        Test.stopTest();
        
        List<Release_Playbook_Sub_Item__c> subItems = [SELECT Id FROM Release_Playbook_Sub_Item__c];
        System.assertEquals(0, subItems.size(), 'Should have no sub items');
    }
}