force-app/main/default/objects/copado__Org__c/fields/branch__c.field-meta.xml
<CustomField>
    <fullName>branch__c</fullName>
    <formula>copado__Environment__r.Git_base_branch__r.copado__Branch__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/copado__Org__c/fields/Weekly_PMD_Report__c.field-meta.xml
<CustomField>
    <fullName>Weekly_PMD_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Weekly PMD Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PMDReport1.cls
public class PMDReport1 {
    @future(callout=true) 
    public static void orgscan() { 
        // Query the copado__Org__c records which has Weekly_PMD_Report__c = true
      /*  List<copado__Org__c> orgs = [SELECT Id, Name, Weekly_PMD_Report__c, branch__c FROM copado__Org__c 
                                     WHERE Weekly_PMD_Report__c = true WITH SECURITY_ENFORCED];
        Userstorysfsca.dispatchOrgScan(orgs);  */
    }  
}