force-app/main/default/objects/copado__Step__c/fields/Permormed_by__c.field-meta.xml
<CustomField>
    <fullName>Permormed_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Provide the user who has performed the Manual Task</inlineHelpText>
    <label>Performed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Performed_by</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/copado__Step__c/fields/Validated_By__c.field-meta.xml
<CustomField>
    <fullName>Validated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Validated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Validated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/copado__Step__c/fields/Validation_Request__c.field-meta.xml
<CustomField>
    <fullName>Validation_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please provide the request for the Step Validation</inlineHelpText>
    <label>Validation Request</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Validation_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deployment_Task_Tracker__c/Deployment_Task_Tracker__c.object-meta.xml
<CustomObject>
    <label>Deployment Task Tracker</label>
    <nameField>
        <displayFormat>DTT-{000000}</displayFormat>
        <label>Deployment Task Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Task Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Deployment_Task_Tracker__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment</label>
    <referenceTo>copado__Environment__c</referenceTo>
    <relationshipLabel>Deployment Task Trackers</relationshipLabel>
    <relationshipName>Deployment_Task_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deployment_Task_Tracker__c/fields/Performed_by__c.field-meta.xml
<CustomField>
    <fullName>Performed_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Performed by the User</inlineHelpText>
    <label>Performed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DTT_Performed_by</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deployment_Task_Tracker__c/fields/Validated_By__c.field-meta.xml
<CustomField>
    <fullName>Validated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Validated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DTT_Validated_By</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/tasktracker.cls
public with sharing class tasktracker {
    public static void taskCreate(Id jobStepId) {
        /*
        // List to hold new records to be inserted
        List<Deployment_Task_Tracker__c> recordsToInsert = new List<Deployment_Task_Tracker__c>(); */
        Deployment_Task_Tracker__c newRecord = new Deployment_Task_Tracker__c();

        // Query the copado__Step__c object based on the provided jobStepId
        copado__Step__c step = [SELECT Id, Name, copado__Status__c, Validated_By__c,copado__Type__c,
                                Validation_Request__c, Permormed_by__c,copado__Deployment__r.copado__Promotion__r.copado__Destination_Environment__r.name
                                FROM copado__Step__c 
                                WHERE Id = :jobStepId];

        System.debug('Step details: ' + step);
        if (step.copado__Status__c == 'Completed Successfully' && step.copado__Type__c == 'Manual Task'){
            System.debug('completed success record is fetched');
            newRecord.task_name__C = step.name;
            newRecord.Environment__c = step.copado__Deployment__r.copado__Promotion__r.copado__Destination_Environment__c;
            newRecord.Performed_by__c = step.Permormed_by__c;
            newRecord.Validated_By__c = step.Validated_By__c;
        }
        else{
            System.debug('not compeleted successfully');
        }
        System.debug('Insert Record ===  '+newRecord);
        Insert newRecord;
        }
    }