force-app/main/default/objects/copado__Release__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/copado__User_Story__c/fields/Jira_Key__c.field-meta.xml
<CustomField>
    <fullName>Jira_Key__c</fullName>
    <label>Jira Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/copado__User_Story__c/fields/Priority_Severity__c.field-meta.xml
<CustomField>
    <fullName>Priority_Severity__c</fullName>
    <label>Priority/Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Assignment__c/Release_Assignment__c.object-meta.xml
<CustomObject>
    <label>Release Assignment</label>
    <nameField>
        <displayFormat>RAN-{000000}</displayFormat>
        <label>Release Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Assignment__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Release_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Assignment__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Assignments</relationshipLabel>
    <relationshipName>Release_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/Release_Playbook__c.object-meta.xml
<CustomObject>
    <label>Release Playbook</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Release Playbook Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>copado__Deployment_Flow__c</referenceTo>
    <relationshipLabel>Release Playbooks</relationshipLabel>
    <relationshipName>Release_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/fields/Release_Template__c.field-meta.xml
<CustomField>
    <fullName>Release_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Template</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Playbooks</relationshipLabel>
    <relationshipName>Release_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CopadoReleaseControllerTest.cls
@isTest
private class CopadoReleaseControllerTest {
    
    @isTest
    static void testGetUserStories() {
        // Create or query the necessary data
        copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(Name = 'Test Pipeline');
        insert pipeline;
        
        Release_Playbook__c releaseTemplate = new Release_Playbook__c(Status__c = 'In Progress');
        insert releaseTemplate;
        
        Release_Playbook__c playbook = new Release_Playbook__c(Pipeline__c = pipeline.Id, //Use the created Pipeline ID
                                                               Status__c = 'Not Started',
                                                               Release_Template__c = releaseTemplate.Id // Use the correct ID
                                                              );
        insert playbook;
        
        copado__Release__c release = new copado__Release__c(Name = 'Test Release', Release_Playbook__c = playbook.Id);
        insert release;
        
        copado__Team__c team = new copado__Team__c(Name = 'Test Team');
        insert team;
        
        copado__User_Story__c userStory = new copado__User_Story__c(Jira_Key__c = 'TEST-123',
                                                                    Priority_Severity__c = 'High',
                                                                    RecordTypeId = Schema.SObjectType.copado__User_Story__c.getRecordTypeInfosByName().get('User Story').getRecordTypeId(),
                                                                    copado__User_Story_Title__c = 'Test Story Title', copado__Team__c = team.Id,
                                                                    copado__Release__c = release.Id);
        insert userStory;
        
        Test.startTest();
        List<CopadoReleaseController.UserStoryWrapper> result = CopadoReleaseController.getUserStories(playbook.Id);
        Test.stopTest();
        
        System.assertEquals(1, result.size());
    }
    
    @isTest
    static void testGetCopadoReleases() {
        // Create or query the necessary data
        copado__Deployment_Flow__c deploymentFlow = new copado__Deployment_Flow__c(Name = 'FSC Salesforce');
        insert deploymentFlow;
        
        copado__Project__c project = new copado__Project__c(Name = 'Test Project', copado__Deployment_Flow__c = deploymentFlow.Id);
        insert project;
        
        copado__Release__c release = new copado__Release__c(Name = 'Test Release', copado__Project__c = project.Id);
        insert release;
        
        Test.startTest();
        List<CopadoReleaseController.ReleaseWrapper> result = CopadoReleaseController.getCopadoReleases();
        Test.stopTest();
        
        System.assertEquals(1, result.size());
        System.assertEquals(release.Name, result[0].releaseName);
    }
    
    @isTest
    static void testSaveRelease() {
        // Create or query the necessary data
        copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(Name = 'Test Pipeline');
        insert pipeline;
        
        Release_Playbook__c releaseTemplate = new Release_Playbook__c(Status__c = 'In Progress');
        insert releaseTemplate;
        
        Release_Playbook__c playbook = new Release_Playbook__c(Pipeline__c = pipeline.Id, // Use the created Pipeline ID
                                                               Status__c = 'Not Started',
                                                               Release_Template__c = releaseTemplate.Id // Use the correct ID
                                                              );
        insert playbook;
        
        copado__Release__c release1 = new copado__Release__c(Name = 'Release1', copado__Status__c = 'Draft');
        insert release1;
        
        copado__Release__c release2 = new copado__Release__c(Name = 'Release2', copado__Status__c = 'Planned');
        insert release2;
        
        List<Id> releaseIds = new List<Id>{release1.Id, release2.Id};
            
            Test.startTest();
        CopadoReleaseController.saveRelease(playbook.Id, releaseIds);
        Test.stopTest();
        
        release1 = [SELECT Release_Playbook__c FROM copado__Release__c WHERE Id = :release1.Id];
        release2 = [SELECT Release_Playbook__c FROM copado__Release__c WHERE Id = :release2.Id];
        
        System.assertEquals(playbook.Id, release1.Release_Playbook__c);
        System.assertEquals(playbook.Id, release2.Release_Playbook__c);
    }
    
    @isTest
    static void testFetchReleases() {
        // Create test data
        copado__Project__c project = new copado__Project__c(Name = 'Test Project');
        insert project;
        
        copado__Release__c release1 = new copado__Release__c(Name = 'Test Release 1',copado__Status__c = 'Draft',
                                                             copado__Project__c = project.Id);
        
        copado__Release__c release2 = new copado__Release__c(Name = 'Another Release',copado__Status__c = 'Draft',
                                                             copado__Project__c = project.Id);
        insert new List<copado__Release__c>{ release1, release2 };
            Test.startTest();
        List<CopadoReleaseController.ReleaseWrapper> releasesWithSearchKey = CopadoReleaseController.fetchReleases('Test');
        System.assertEquals(0, releasesWithSearchKey.size());
        
        // Test without searchKeyR
        List<CopadoReleaseController.ReleaseWrapper> allReleases = CopadoReleaseController.fetchReleases('');
        System.assertEquals(0, allReleases.size());
        Test.stopTest();
    }
    
    
    @isTest
    static void testGetAllUsers() {
        // Create test data
        User testUser = [SELECT Id, Name FROM User LIMIT 1];
        
        Test.startTest();
        List<User> result = CopadoReleaseController.getAllUsers();
        Test.stopTest();
        
        System.assert(!result.isEmpty());
    }
    
    @isTest
    static void testFetchUsers() {
        // Create test data
        User testUser = [SELECT Id, Name FROM User LIMIT 1];
        
        Test.startTest();
        List<User> result = CopadoReleaseController.fetchUsers(testUser.Name);
        Test.stopTest();
        
        System.assertEquals(1, result.size());
    }
    
    @isTest
    static void testSaveReleaseAssignments() {
        // Create or query the necessary data
        copado__Deployment_Flow__c pipeline = new copado__Deployment_Flow__c(Name = 'Test Pipeline');
        insert pipeline;
        
        Release_Playbook__c releaseTemplate = new Release_Playbook__c(Status__c = 'In Progress');
        insert releaseTemplate;
        
        Release_Playbook__c playbook = new Release_Playbook__c(Pipeline__c = pipeline.Id, // Use the created Pipeline ID
                                                               Status__c = 'Not Started',
                                                               Release_Template__c = releaseTemplate.Id // Use the correct ID
                                                              );
        insert playbook;
        
        User testUser = [SELECT Id FROM User LIMIT 1];
        List<Id> userIds = new List<Id>{testUser.Id};
            
            Test.startTest();
        try{
            CopadoReleaseController.saveReleaseAssignments(playbook.Id, userIds);
        } catch(exception e){
            System.debug('Exception thrown: ' + e.getMessage());
            System.debug('Stack Trace: ' + e.getStackTraceString());
        }
        Test.stopTest();
        
        List<Release_Assignment__c> assignments = [SELECT Id, Release_Playbook__c, Name__c FROM Release_Assignment__c WHERE Release_Playbook__c = :playbook.Id];       
        System.assertEquals(0, assignments.size());
    } 
}