force-app/main/default/objects/Activity/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment</label>
    <referenceTo>copado__Environment__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Assignment__c/Release_Assignment__c.object-meta.xml
<CustomObject>
    <label>Release Assignment</label>
    <nameField>
        <displayFormat>RAN-{000000}</displayFormat>
        <label>Release Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Assignment__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Release_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Assignment__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Assignments</relationshipLabel>
    <relationshipName>Release_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Assignment__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Release Lead</fullName>
            </value>
            <value>
                <fullName>Tech Lead</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Dev Lead</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
            <value>
                <fullName>FSC PO</fullName>
            </value>
            <value>
                <fullName>DevOps Lead</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/Release_Playbook__c.object-meta.xml
<CustomObject>
    <label>Release Playbook</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Release Playbook Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>copado__Deployment_Flow__c</referenceTo>
    <relationshipLabel>Release Playbooks</relationshipLabel>
    <relationshipName>Release_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/fields/Release_Playbook_Name__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook_Name__c</fullName>
    <label>Release Playbook Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/fields/Release_Template__c.field-meta.xml
<CustomField>
    <fullName>Release_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Template</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Playbooks</relationshipLabel>
    <relationshipName>Release_Playbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/Release_Playbook_Item__c.object-meta.xml
<CustomObject>
    <label>Release Playbook Item</label>
    <nameField>
        <displayFormat>RPI-{000000}</displayFormat>
        <label>Release Playbook Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Playbook Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program Governance</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preprod</fullName>
            </value>
            <value>
                <fullName>Prod</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Execution_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Execution_Sequence__c</fullName>
    <label>Execution Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Before Deployment</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>After Deployment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Issues_Comments__c.field-meta.xml
<CustomField>
    <fullName>Issues_Comments__c</fullName>
    <label>Issues/Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Pipeline__c.field-meta.xml
<CustomField>
    <fullName>Pipeline__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pipeline</label>
    <referenceTo>copado__Deployment_Flow__c</referenceTo>
    <relationshipLabel>Release Playbook Items</relationshipLabel>
    <relationshipName>Release_Playbook_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Release_Playbook__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook__c</fullName>
    <label>Release Playbook</label>
    <referenceTo>Release_Playbook__c</referenceTo>
    <relationshipLabel>Release Playbook Items</relationshipLabel>
    <relationshipName>Release_Playbook_Items1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Release_Playbook_Template_Item__c.field-meta.xml
<CustomField>
    <fullName>Release_Playbook_Template_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Release Playbook Template Item</label>
    <referenceTo>Release_Playbook_Item__c</referenceTo>
    <relationshipLabel>Release Playbook Items</relationshipLabel>
    <relationshipName>Release_Playbook_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Required_Sub_Item_s__c.field-meta.xml
<CustomField>
    <fullName>Required_Sub_Item_s__c</fullName>
    <label>Required Sub Item(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Deployment Step</fullName>
            </value>
            <value>
                <fullName>Git Snapshot</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Scan Comparison</fullName>
            </value>
            <value>
                <fullName>Snapshot Commit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/SCA__c.field-meta.xml
<CustomField>
    <fullName>SCA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SCA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Prod Deployment</fullName>
            </value>
            <value>
                <fullName>Pre-Deployment</fullName>
            </value>
            <value>
                <fullName>Deployment</fullName>
            </value>
            <value>
                <fullName>Go Live</fullName>
            </value>
            <value>
                <fullName>Post Go Live</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Release_Playbook_Item__c/fields/Task_Description__c.field-meta.xml
<CustomField>
    <fullName>Task_Description__c</fullName>
    <label>Task Description</label>
    <length>50768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ReleasePlaybookController.cls
public with sharing class ReleasePlaybookController {
    
    public class ReleasePlaybookWrapper {
        @AuraEnabled
        public Release_Playbook__c playbook { get; set; }
        @AuraEnabled
        public String pipelineName { get; set; }
        @AuraEnabled
        public String status { get; set; }
        @AuraEnabled 
        public Id Id { get; set; }
        @AuraEnabled 
        public String name { get; set; }
        @AuraEnabled 
        public String playbookName { get; set; }
        
        public ReleasePlaybookWrapper(Release_Playbook__c playbook) {
            this.playbook = playbook;
            this.pipelineName = playbook.Pipeline__r != null ? playbook.Pipeline__r.Name : null;
            this.status = playbook.Status__c;
            this.id = playbook.Id;
            this.name = playbook.Name;
            this.playbookName = playbook.Release_Playbook_Name__c;
        }
    }
    
    @AuraEnabled
    public static List<ReleasePlaybookWrapper> getTemplateRecs() {
        List<Release_Playbook__c> playbooks = [SELECT Id, Name, Pipeline__r.Name,Release_Template__c,Status__c FROM Release_Playbook__c 
                                               WHERE RecordType.Name = 'Release Playbook Template'];
        System.debug('Release Play Book Items are: ++++++ : ' + playbooks);
        
        List<ReleasePlaybookWrapper> wrappers = new List<ReleasePlaybookWrapper>();
        for (Release_Playbook__c playbook : playbooks) {
            wrappers.add(new ReleasePlaybookWrapper(playbook));
        }
        System.debug('Returning PlayBook are: ++++++ : ' + wrappers);
        return wrappers;
    }
    
    @AuraEnabled
    public static void createReleasePlaybookItems(Id releasePlaybookId, Id selectedTemplateId) {
        System.debug('Release Playbook ID: ' + releasePlaybookId);
        System.debug('Selected Template IDs: ' + selectedTemplateId);
        if (selectedTemplateId == null) {
            throw new AuraHandledException('No template IDs provided.');
        }
        try {
            // Check if items already exist for the given releasePlaybookId
            Integer existingItemCount = [SELECT COUNT() FROM Release_Playbook_Item__c WHERE Release_Playbook__c = :releasePlaybookId];
            if (existingItemCount > 0) {
                throw new AuraHandledException('Items already exist for the selected release playbook.');
            }
            
            Release_Playbook__c selectedTemplates = [SELECT Id, Name, Pipeline__c, Release_Template__c, Status__c
                                                     FROM Release_Playbook__c WHERE Id = :selectedTemplateId LIMIT 1];
            System.debug('Selected Templates: +++++ :' + selectedTemplates);
            if (selectedTemplates == null) {
                throw new AuraHandledException('Selected template items not found.');
            }
            
            // Query the child templates related to the selected templates
            List<Release_Playbook_Item__c> childTemplates = [SELECT Id, Name, Area__c, Execution_Sequence__c,  Environment__c,
                                                             End_Date_Time__c, Issues_Comments__c, Order__c, Pipeline__r.Name, SCA__c, 
                                                             Release_Playbook__c, Stage__c, Start_Date_Time__c, Status__c, Required_Sub_Item_s__c,
                                                             Task_Description__c, Release_Playbook_Template_Item__c FROM 
                                                             Release_Playbook_Item__c WHERE RecordType.Name = 'Release Item Templates' 
                                                             AND Release_Playbook__c = :selectedTemplates.Id];
            System.debug('Child Templates: ' + childTemplates);
            List<Release_Playbook_Item__c> newItems = new List<Release_Playbook_Item__c>();
            for (Release_Playbook_Item__c template : childTemplates) {
                Release_Playbook_Item__c newItem = new Release_Playbook_Item__c();
                newItem.Release_Playbook__c = releasePlaybookId;
                newItem.Area__c = template.Area__c;
                newItem.Required_Sub_Item_s__c = template.Required_Sub_Item_s__c;
                newItem.SCA__c = template.SCA__c;
                newItem.Environment__c = template.Environment__c;
                newItem.Execution_Sequence__c = template.Execution_Sequence__c;
                newItem.Issues_Comments__c = template.Issues_Comments__c;
                newItem.Order__c = template.Order__c;
                newItem.Stage__c = template.Stage__c;
                newItem.Status__c = template.Status__c;
                newItem.Task_Description__c = template.Task_Description__c;
                // Setting the self-lookup field to reference the template record
                newItem.Release_Playbook_Template_Item__c = template.Id;  // Replace 'Template_Lookup__c' with your actual field name
                newItem.RecordTypeId = Release_Playbook_Item__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('Release Activity').getRecordTypeId();
                newItems.add(newItem);
                System.debug('List of new Items : ++++ ' + newItems);
            }
            
            List<Release_Assignment__c> templateReleaseAssignees = [SELECT Id, Name__c, Company__c, Contact__c, Email__c, RecordType.Name, 
                                                                    Release_Playbook__c, Role__c FROM Release_Assignment__c 
                                                                    WHERE RecordType.Name = 'Template Release Assignments' 
                                                                    AND Release_Playbook__c = :selectedTemplates.Id];
            System.debug('templateReleaseAssignees are: +++++ ' + templateReleaseAssignees);
            
            List<Release_Assignment__c> newReleaseAssign = new List<Release_Assignment__c>();
            for (Release_Assignment__c templateReleaseAssign : templateReleaseAssignees) {
                Release_Assignment__c newAssign = new Release_Assignment__c();
                newAssign.Name__c = templateReleaseAssign.Name__c;
                newAssign.Company__c = templateReleaseAssign.Company__c;
                newAssign.Contact__c = templateReleaseAssign.Contact__c;
                newAssign.Email__c = templateReleaseAssign.Email__c;
                newAssign.Release_Playbook__c = releasePlaybookId;
                // Fetching the RecordTypeId
                Id recordTypeId = Release_Assignment__c.sObjectType.getDescribe().getRecordTypeInfosByName().get('Assignment Users').getRecordTypeId();
                System.debug('Record Type ID for Assignment Users: ' + recordTypeId);
                newAssign.RecordTypeId = recordTypeId;
                newAssign.Role__c = templateReleaseAssign.Role__c;
                newReleaseAssign.add(newAssign);
                System.debug('List of new TemplateItems : ++++ ' + newReleaseAssign);
            }
            
            insert newReleaseAssign;
            System.debug('List of new TemplateItems : ++++ ' + newReleaseAssign);
            
            if (!newItems.isEmpty()) {
                System.debug('List of new Items in If Condition : ++++ ' + newItems);
                insert newItems;
            } else {
                throw new AuraHandledException('No new Release Playbook Template records to process.');
            }
        } catch (Exception e) {
            throw new AuraHandledException('Error creating Release Playbook Items: ' + e.getMessage());
        }
    }
    
}